### ISSUE TITLE
Support TypeScript 2.0 Development?

### ISSUE THREAD

**Issue by danielstern** [TypeStrong/atom-typescript#1003]
I'm developing a project in TypeScript 2.0, but at the current time Atom-TypeScript is on 1.8.0.

I'm not sure if there's any way this can be changed? Atom-TypeScript should support TS 2.0 development since, in addition to having new features that are useful, it would encourage development using latest standards.

**Comment by dsifford** [comment]
@danielstern You can use typescript 2.0.x features if you link the globally installed typescript 2 `typescriptServices.js` file to the package on the settings page.

![image](https://cloud.githubusercontent.com/assets/5240018/16738915/baec40c4-4765-11e6-806a-36298e5748e4.png)

**Comment by thomasboyt** [comment]
As someone who works on mostly 1.x projects who's slowly porting some things to 2.0, it'd be great to be able to specify this differently for different projects. I suppose that would rely on https://github.com/atom/atom/issues/5168, though :(

I locally install TypeScript for each project I work on (since I never use the command-line compiler), so the ability to look up a local `typescript` module relative to the same folder as the found `tsconfig.json` would also fix this issue for me.

**Comment by DeusProx** [comment]
@dsifford I tried to use a new feature of ts 2.0 which enables you to use imports with a path which starts from project-root. I wasn't able to use atom for this as atom-typescript also chokes on the config. maybe this is also with another ticket. ATM I just had to switch to VS Code for that project

**Comment by danielstern** [comment]
Maybe we can specify a path in the `package.json` file, or another appropriate config file? I'd be happy to put together a PR if this makes sense

**Comment by thomasboyt** [comment]
I don't think you'd need a specified path, since you can install TypeScript locally to a project like any other Node module. I *think* what you'd want is:

1. Find root `package.json` for the project
2. Check if `typescript` is specified in `devDependencies` or `dependencies`
3. If so, use the `typescript` installed in `project_root/node_modules/typescript`
4. Otherwise, use the TypeScript specified in atom-typescript's settings (defaulting to a globally-installed TypeScript)

It's important to actually check to make sure TS is a specified dependency in the `package.json`, BTW. If you don't, there's an edge case where a user wants to use the default TypeScript installation rather than a local one, but installs a package that happens to install TypeScript as a dependency, and then *that* TypeScript module ends up getting used (since with NPM 3 it'd be installed to `node_modules/typescript`).

**Comment by pwnall** [comment]
[linter-tslint](https://github.com/AtomLinter/linter-tslint) looks for a project-local TypeScript. The code there might be useful as a starting point.

https://github.com/AtomLinter/linter-tslint/blob/master/lib/init.coffee

**Comment by phreed** [comment]
Just to add some clarification to @dsifford recommendation.
It is important to make sure you are getting the correct typescriptServices.js file.
I am using `nvm use v4.4.7`.
Then I install typescript with `npm install typescript@2.0.0`.
This results in the proper typescriptServices.js being installed in the following location:
/home/<me>/.nvm/versions/node/v4.4.7/lib/node_modules/typescript/lib/typescriptServices.js

**Comment by swinc** [comment]
For others running into this issue, note that it is important to get the correct file path. I have both global and separate *local* Typescripts installed in various directories for various projects.

On my first attempt to reference the global `typescriptServices.js` file Atom wouldn't even load the `atom-typescript`module. On my second attempt to use the correct local version, it worked fine. 👍
