### ISSUE TITLE
Unable to check .js files

### ISSUE THREAD

**Issue by ericelliott** [TypeStrong/atom-typescript#1024]
TypeScript supports [type inference](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Type%20Inference.md) with no explicit annotations. Therefore, it should be useful to run the typescript plugin even on `.js` files, but I'm having trouble getting that to work.

Here's my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowNonTsExtensions": true,
  },
  "filesGlob": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "!node_modules/**"
  ]
}
```

## Actual

The following generates errors in a `test.ts` file, but the same contents in a `test.js` file does not activate the TypeScript feedback or raise any errors:

```js
const foo = ({
  bar = 'x',
  baz = 'y'
}) => ({ bar, baz });

const bif = foo({
  bar: 1,
  baz: []
});

console.log(bif);
```

## Expected

I should be able to see type errors in `.js` files.

**Comment by basarat** [comment]
Sadly, atom-typeScript is currently only designed to work on .ts files. Closing in favor of : https://github.com/TypeStrong/atom-typescript/issues/315#issuecomment-176500256

If you want to work on it I'm happy have you tackle it :rose:

**Comment by basarat** [comment]
FWIW using TypeScript to power JavaScript is not as good as one might think. This is because JavaScript offers very low guarantees about what is and isn't *allowed code*. TypeScript essentially forces devs to document what their intentions are so that they don't shoot themselves (or other developers) in the foot. This results in better tooling. 

One can see the difference in developer experience here : https://youtu.be/gmKXXI_ck7w?t=2m35s :rose:
