### ISSUE TITLE
Analysis of .ts files is very slow

### ISSUE THREAD

**Issue by justinfagnani** [TypeStrong/atom-typescript#1037]
Since upgrading to 10.1.5 analysis of .ts files has become unbearably slow.

After just a few small edits to a singlefile, the circular spinner in the atom-typescript will show several hundred pending requests and spin for many seconds. It's easy to get ~1000 pending requests queued up, and sometimes the count appears stuck.

If I look at the requests there any many lines of editText, errorsForFile, getProjectFileDetails. Not knowing how the plug-in works, editText seems reasonable, though it seems like there are usually far more than even the number of keystrokes I've made, but multiple calls to errorsForFile and getProjectFileDetails for edits to one file seem unnecessary?

Anyway, this is a new and severe performance regression. If there's anyway I can help diagnose, I'm very happy to. I haven't been able to take a profile that shows anything obvious. A colleague has had the same problem, so it could be project setup related.

**Comment by greglockwood** [comment]
This issue has made the plugin nigh on unusable for me. I will open up Atom which restores my previous session with all the many, many tabs I have open, and immediately just fail to load because of this plugin. Eventually it shows the "Editor is not responding... Keep waiting or Close" dialog.

If I start a second Atom window and disable the atom-typescript plugin in Settings, I can then reopen the folder for the TS project I was working on with no issues. It opens fast and all my tabs are still there.

As soon as I then try to re-enable the atom-typescript plugin, though, the editor freezes again and I have to force close it or wait for the dialog to allow me to close it.

However, when I did the same series of steps as before (open new Atom window, disable plugin, reopen project folder in Atom), but this time closed all but one tab for a TS file _before_ enabling the atom-typescript plugin, it does not lock up the application and I can actually use it. It does noticeably pause (the file is 562 lines), but then recovers and I can proceed as normal.

So it seems that the plugin is trying too eagerly to process all tabs on startup, when that could potentially be done either lazily when the tab is first activated, or in a staggered manner after startup, prioritising the active tab first. I don't know if either is possible, but it would make a difference to tab whores like me - I feel like the editor by default encourages accumulating tabs because many actions open new tabs and it takes active effort by the user to close ones not needed, so I imagine this is a pretty common scenario and thus one that needs to be dealt with.

**Comment by justinfagnani** [comment]
Any update here? I'm afraid I'm going to have to move to VS Code soon :(

**Comment by paulintrognon** [comment]
I was just doing the quickstart of the Angular2 tutorial, so I got only 4 tiny .ts files opened, and everytime I write a new line of code, dozens of Pending Requests stack up, even hundreds if I type a few lines, making the plugin useless (it's showing me errors I corrected minutes ago, etc.)

I just installed the plugin, and have not touched the configuration.

The plugin looks awesome though, can't wait to be able to use it properly!

**Comment by justinfagnani** [comment]
@basarat any ideas? This is making Atom nearly unusable.

**Comment by justinfagnani** [comment]
Bueler? Can the anyone working on atom-typescript at least acknowledge whether or not this is something that they're aware of and/or planning on working on?

This is effectively breaking features like Jump-to-definition, since that seems to need to wait for the pending requests to complete, and there's always a huge queue of pending requests...

**Comment by justinfagnani** [comment]
I figured out my problem at least: I had a comment in `tsconfig.json`, which `tsc` explicitly allows, but apparently atom-typescript doesn't. The comments caused autom-typescript to fall back on some default behavior that probably processed all of node_modules/, and thus the slow updates.

**Comment by maxime1992** [comment]
@justinfagnani i'm struggling with atom and typescript ... It's so slow that it's killing me ...
It take 20 to 40s to have autocompletion in my project. (built with angular-cli).
I'm pretty sure that atom is not (fully ?) taking my configuration into account.

Can you give me more details on how to solve this ?

I tried many things and here's my tsconfig.json : 

```json
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es6",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "typeRoots": [
      "../node_modules/@types"
    ],
    "inlineSources": true
  },
  "filesGlob": [
    "!node_modules",
    "node_modules/@types/**/*.d.ts",
    "src/**/*.d.ts",
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "coverage"
  ],
  "atom": {
    "rewriteTsconfig": true
  },
  "files": []
}
```

**Comment by normandjulian** [comment]
I just found that #1060 

Try to add in your tsconfig.json the option exclude, see below 

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [ "node_modules" ]
}
`

**Comment by arlowhite** [comment]
Similar to #1078 

From what I've read in issues and docs, I thought atom-typescript uses the **autocomplete-plus** and **linter** packages for this kind of thing. But when I change settings such as "Show Suggestions On Keystroke" it has no effect.

I haven't seen any official developer comment on these performance issues either.   :-(

**Comment by arlowhite** [comment]
Just updated Atom to **1.11.2**; it seems much faster, try upgrading Atom and see if your performance improves.
[Atom Releases Changelog](https://atom.io/releases)

**Comment by app-sparkler** [comment]
As of now, the solution in this [stackoverflow thread](http://stackoverflow.com/a/39406423/4742733) worked for me.  

Good Luck.

**Comment by melkishengue** [comment]
Works for me, thanks! 👍
