### ISSUE TITLE
Endless "Pending Requests" 

### ISSUE THREAD

**Issue by aderbas** [TypeStrong/atom-typescript#1146]
After the last update (10.1.12) my project (Angular 2) passed the stands with "Request Pendings" infinite and the number only increases. Nothing works, like auto complete and error highlighting.

![pending_error](https://cloud.githubusercontent.com/assets/12519019/20600429/67c902c8-b232-11e6-91e8-aac0cde9345c.png)

tsconfig.json
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```
Typescript 2.0.2
Ubuntu 14.04 - 64
Atom 1.11.2

**Comment by aderbas** [comment]
![pending_error](https://cloud.githubusercontent.com/assets/12519019/20608295/48eeba3c-b25f-11e6-9d22-11517e708f92.png)

**Comment by aderbas** [comment]
Version 1.12.5 solve this.

**Comment by aderbas** [comment]
Update Atom version did not solved =/

**Comment by isaacg11** [comment]
i'm experiencing the same endless "Pending Requests" issue, and I have version 1.12.5. Writing in TypeScript/Angular, issue just started out of nowhere. It will not compile my TypeScript to JavaScript on save like it normally does.

**Comment by aderbas** [comment]
@isaacg11 I'm tired, I'm using [VSCode](https://code.visualstudio.com/) for Angular 2 and TypeScript. Take a look.

**Comment by guncha** [comment]
Look, guys, why don't you take a look at what the issue is? I'm not using Angular 2 so I'm not aware of these types of issues. If you figure out a fix, I'll gladly review and merge, though.

**Comment by yagao0o** [comment]
@guncha 

![pending-error](https://cloud.githubusercontent.com/assets/4001379/20745684/55790344-b71d-11e6-9eda-b252ba27aed4.jpeg)
It seems it's repeating do these things endless.   
Open developer tools:

```
ts worker restarting. Don't know why it stopped with code: 1
CHILD ERR STDERR: module.js:457
    throw err;
    ^

Error: Cannot find module '/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
```

and
```
workerLib.js:28 Uncaught (in promise) Error: No worker active to recieve message: getProjectFileDetails
    at Parent.RequesterResponder.sendToIpcHeart (/Users/Luyz/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:28:39)
    at Object.getProjectFileDetails (/Users/Luyz/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:107:47)
    at MainPanelView.updateFileStatus (/Users/Luyz/.atom/packages/atom-typescript/dist/main/atom/views/mainPanelView.js:188:16)
    at /Users/Luyz/.atom/packages/atom-typescript/dist/main/atomts.js:61:37
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

hope this helps.

**Comment by isaacg11** [comment]
Okay, I manually updated this package in Atom and it now works! I'm on a Mac too for everyone who is experiencing the same thing on OSX. Just to packages and update this one!

**Comment by tjoskar** [comment]
@guncha, I don't think it is a angular specific problem. This is an old issue, just take a look at these issues: [624](https://github.com/TypeStrong/atom-typescript/issues/624), [349](https://github.com/TypeStrong/atom-typescript/issues/349), [556](https://github.com/TypeStrong/atom-typescript/issues/556), [657](https://github.com/TypeStrong/atom-typescript/issues/657), [730](https://github.com/TypeStrong/atom-typescript/issues/730), [873](https://github.com/TypeStrong/atom-typescript/issues/873), [917](https://github.com/TypeStrong/atom-typescript/issues/917), [969](https://github.com/TypeStrong/atom-typescript/issues/969). I can (from time to time) get endless of pending request even for non-angular projects. 

The issue usually occurs for three different reasons:
1. Atom updates (I have turn off auto-updates)
2. If I don't restart Atom for a few days.
3. If I write code with a lot of errors in it. Let's say I have the following class:
```javascript
class MyClass {
  if (something) {
    ...
  }
  console.log('Hi');
}
```
`atom-typescript` will tell me that I'm doing it wrong (which I am) but if I don't care about the errors and just continue, the "Pending Requests" will soon start to grow. 

So if I don't update Atom, quit Atom every night and fix the errors that `atom-typescript` points out right away. `atom-typescript` usual works for me whiteout a growing list of "Pending Requests".

**Comment by isiahmeadows** [comment]
BTW, this isn't necessarily platform-specific. I've repro'd it on both macOS and Linux.

It happens any time there's a large number of errors, and here's my guess as to what's going on, based on a cursory glance at the source (I'm not that familiar with it):

1. It starts a task and adds it to a queue.
2. At an overflow point, it receives a message pointing to the wrong task, so it dequeues it and gets the wrong thing.

I honestly can't tell if it's this library, TS, or both. I suspect the bug is either [here](https://github.com/TypeStrong/atom-typescript/blob/master/lib/client/client.ts#L132-L155) or related to that segment.

**Comment by isiahmeadows** [comment]
Bumping, because I've experienced it much more recently, and initially developed the habit to keep my Activity Monitor running to regularly kill this plugin's worker. (It's then developed other uses, like repeatedly killing linter-eslint's worker when I'm working on local ESLint rules.) I've also since disabled the plugin while waiting for a fix.

So if it's been fixed, please let me know, so I know I can re-enable the plugin.

**Comment by lierdakil** [comment]
A lot of code has been changed or straight up rewritten in the last couple years. I personally use Atom-TypeScript quite a bit, and didn't encounter anything resembling the issue described here for a long time. But I do restart Atom at least once per day, and restart tsserver even more often (because it can be bad at dealing with changes to fs, so `git checkout another-branch` can and often does utterly confuse it). I've even added `typescript:restart-all-servers` command to make the latter easier.

So, as I see it, there are two possibilities: either the issue was accidentally fixed at some point, or I'm just not doing something that triggers the issue.

The former is possible, although the last meaningful change to the code most likely responsible for anything to do with this issue didn't have any non-trivial changes for over a year.

In case it's the latter, unless someone bothers to cobble together a minimal testcase and/or write a detailed reproduction guide, I'm afraid nothing is going to change here, because if I can't figure out what's wrong, I can't fix it, and I can't figure out what's wrong if I can't even reproduce the issue.

On the topic of overflow, I _really_ don't think it's that. See, even at a sustained 30 million requests per second (which is, to say the least, a ridiculous load for a single-user application), JS numbers are robust enough to work without issue for almost 10 years for unique queue identifiers. So numeric overflow is really unlikely to even happen on reasonable timescales.
