### ISSUE TITLE
Installs correctly, but won't run

### ISSUE THREAD

**Issue by benvmatheson** [TypeStrong/atom-typescript#1217]
The package seems to have installed correctly, but doesn't appear to be running.

I'm seeing the following in the console when the package is enabled:
Uncaught (in promise) Error: Missing filePath or not a Typescript file(…)   typescriptBuffer.js:75

**Comment by Xakaloz** [comment]
Same thing here. Doesn't compile nor rewrites tsconfig file.

**Comment by guncha** [comment]
@benvmatheson the error means that either you haven't saved your file yet or the grammar is not set to `Typescript`. In both of those cases, the plugin will no do anything.

@Xakaloz if you mean the behavior of `compileOnSave`, then it's different from the previous version. Unless set to `true` in `tsconfig.json`, it will not emit anything. It also doesn't rewrite the `tsconfig` file anymore because it supports all the options Typescript does so no need to update the `files` array, for example.

**Comment by clickthisnick** [comment]
It is not working for me either now, I recently updated to the Linter 2.0, I'm wondering if this is causing issues?

**Comment by Xakaloz** [comment]
@guncha Yes, i mean the `"rewriteTsconfig": true` option.

I have to manually add new files to `files` array in order to have the compilation working.

If I just use the `filesGlob` property, I have "Duplicate identifier" errors with Linter 2.0.

Here you have my tsconfig.json configuration, maybe I am doing something wrong or misunderstanding some subtility:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "target": "es5",
    "outFile": "js/app.js",
    "sourceMap": true,
    "module": "system",
    "allowJs": true
  },
  "filesGlob": [
    "**/*.ts",
    "!node_modules/**"
  ],
  "files": [
    "ts/app.ts",
    "ts/ApplicationMain.ts",
    "ts/utils/ClassUtils.ts",
    "ts/components/AbstractComponent.ts",
    "ts/components/MainFooter.ts",
    "ts/components/MainMenu.ts",
    "typings/index.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": true
  }
}
```

Thank you.

**Comment by roberto-naharro** [comment]
@Xakaloz I have the same problem. I fixed it temporally installing this node package globally (to avoid affecting my code):
https://github.com/wjohnsto/tsconfig-glob

Hope this helps you ;)

**Comment by guncha** [comment]
@Xakaloz, right, there's no atom-typescript specific `rewriteTsconfig` option because the compiler can now do what that option was solving. `filesGlob` was also plugin specfic and is now gone. What you need to use instead is `include` and `exclude`, e.g.,

```json
{
    "compilerOptions": {
      "noImplicitAny": true,
      "removeComments": true,
      "preserveConstEnums": true,
      "target": "es5",
      "outFile": "js/app.js",
      "sourceMap": true,
      "module": "system",
      "allowJs": true
    },
    "include": [
        "ts/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

You probably got the duplicate identifier errors because by default Typescript will use all `.ts` files in the project.

**Comment by Xakaloz** [comment]
Thank you, it's working like expected now !
