### ISSUE TITLE
Code formatting settings not recognized anymore

### ISSUE THREAD

**Issue by h-arlt** [TypeStrong/atom-typescript#1218]
Since v11, code formatting settings such as `formatOnSave` or options like `indentSize`, `tabSize` etc. are not recognized anymore.

**Comment by guncha** [comment]
Sounds about right. With the update, it'll use your `indentSize` settings from Atom for that specific file, but that's about it. This is on my TODO list, but I can't say it has a high priority so it's up for grabs for anyone.

**Comment by Wandang** [comment]
Well the entire onSaveHandler.js was kicked. For now you can resort to using 'alt+cmd+L' or 'alt+ctrl+L' manually.

Was there any reason why this file was omitted?

Guess I will just build myself an atom trigger that procs on every save in the meantime.

**Comment by guncha** [comment]
The reason was to keep things simple. I ported the format command over, but as @h-arlt alluded, it doesn't use the settings from `tsconfig.json` file yet. If people really want `formatOnSave`, it will be clear from issues like this and me or someone else will implement it, so thanks for your input.

Atom is very hackable so, as you mentioned, it shouldn't be hard to set up the trigger.
