### ISSUE TITLE
Auto format is allways set 4 tab indentation

### ISSUE THREAD

**Issue by ASnow** [TypeStrong/atom-typescript#1236]
When I press `Ctrl+Alt+L` code I will get code with 4 space tabs. 
I had editor config Tab Length: 2 space and tsconfig in subdirrectory:
```
  "formatCodeOptions": {
    "indentSize": 2,
    "tabSize": 2,
    "newLineCharacter": "\n",
    "convertTabsToSpaces": true,
    "insertSpaceAfterCommaDelimiter": true,
    "insertSpaceAfterSemicolonInForStatements": true,
    "insertSpaceBeforeAndAfterBinaryOperators": true,
    "insertSpaceAfterKeywordsInControlFlowStatements": true,
    "insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
    "placeOpenBraceOnNewLineForFunctions": false,
    "placeOpenBraceOnNewLineForControlBlocks": false
  }
```

**Comment by ASnow** [comment]
Also have a problem with correct indent size
![2017-04-04 12 25 59](https://cloud.githubusercontent.com/assets/572218/24650027/9e51e984-1931-11e7-8b95-3eb88f471509.png)

**Comment by william-gr** [comment]
+1, I have the same issue and its annoying because all my code has indent of 2 so it became unusable for now.

**Comment by guncha** [comment]
This shouldn't be too hard to add. The format command needs to run `projectInfo` on the file first to get the path to the `tsconfig.json`, read it, parse it to get the options and then pass those to the `format` command. I'll gladly accept PRs or eventually I'll get to it myself since I need it, but it might take some time.
