### ISSUE TITLE
[Resolved] Compile errors not appearing if file is not opened -- How do I enable this?

### ISSUE THREAD

**Issue by JeremyJStarcher** [TypeStrong/atom-typescript#1244]
On my project I have introduced a deliberate error, such as:

    const t: number = true;

If I leave the tab open and press `F6` to build I get the notification via the *linter* that there is an error in my code.

If I close the tab and open another typescript file then press `F6` to buid, I can see the build process run and all of the Javascript files are properly generated.  The message `Emit Success` appears on the status bar.

I have poured through every menu and config option I can find -- where are the build errors displayed at?

(Right now I'm doing the build from the command line and opening the associated files -- which works -- in the same sense that hammering nails with a rock "works.")

**Comment by guncha** [comment]
You're right, the build command doesn't do any type checking. These are two separate actions in the compiler so that's how I implemented them. You might be interested in "Check all files" command that does what you're looking for.

I can see an argument for combining these two, but I haven't personally felt the need for it. I suppose it depends on the workflow. When working on `atom-typescript`, I rarely have to use the build command, instead I rely on compile on save to update any necessary files which is almost instantaneous. I only use Build when I delete the whole `dist` folder and need a clean slate. Either way, I'm open to discussion.

**Comment by JeremyJStarcher** [comment]
My use-case is a little different -- been doing some refactoring to a code base and its nice to see what breaks elsewhere in response to a change I'm making in a file.

The compile-on-save doesn't really help there.

I found "Check all files" tucked away in the command palette and ran it, but I'm not getting a list of errors either.

**Comment by guncha** [comment]
Are you using the new `linter-ui`? They kind of made it hard to see project errors, but you can get them back in the `linter-ui` settings by changing some dropdowns to "Entire Project".

After you configure it properly, this is what it should look like:

![image](https://cloud.githubusercontent.com/assets/679632/25093339/e0bf0396-235f-11e7-8080-5295f8d6dd0a.png)

**Comment by JeremyJStarcher** [comment]
That did it! 

Vunderbar and thank you!

I never would have thought to check the linter settings.
