### ISSUE TITLE
Atom doesn't recognize tsconfig.e2e.json

### ISSUE THREAD

**Issue by micaelmbagira** [TypeStrong/atom-typescript#1250]
I have a e2e folder containing a `tsconfig.e2e.json` but Atom doesn't recognize it and then the `No project` is displayed in the bottom bar. The `@types` are not found then and the related errors are shown up. 
Is it possible to manually specify which tsconfig file to use?

**Comment by guncha** [comment]
Why does the file need to be named `tsconfig.e2e.json`?

The Typescript service has to look up the project from a source file, since that's the only thing that it's given when you open a new editor pane. It traverses the directories and looks for `tsconfig.json` files and if one is found, it makes sure that your open file is included either using `files` or `include` directive. To change the name of the config you'd have to specify it on a file or directory basis, it's kind of like a property of the project, but that's already what `tsconfig.json` is for.
