### ISSUE TITLE
typesciptServices.js got removed, can we have it back or have a way of selecting our own TS version?

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1271]
We used to have typescriptServices.js that I think took care of being "on the right version", however it got removed somewhere around Nov last year, but it's not clear to me of why was that given the commit log.

Could we have that option back? Otherwise, why was it removed?

**Comment by guncha** [comment]
@Goodwine, do you mean the configuration option that set the path to the `typescriptServices.js` file? It was removed because the architecture of the plugin changed where it wasn't necessary anymore. The plugin now will try to find the `typescript` module in the project you're working on and use that and, if one cannot be found, use the default version that ships with the plugin.

The search is done exactly the same as if you had a `require("typescript")` call in the source so to use a specific Typescript version, just install it into the `node_modules` directory.

Does that answer your question?

**Comment by Goodwine** [comment]
It did answer my question. I'm not very familiar with node. I tried installing the typescript version I wanted in a `node_modules` directory as specified in my `$NODE_PATH` but that didn't help.
I deleted `~/.atom/packages/atom-typescript/typescript` and replaced it with my own and it worked, however if I try updating the package, my module will be overwritten, do you have any advice on how to make atom use a custom node package?

**Comment by guncha** [comment]
Hmm, yes, the plugin doesn't seem to take into account `$NODE_PATH` when trying to find the Typescript module. This is a simple fix, hold tight.
