### ISSUE TITLE
..

### ISSUE THREAD

**Issue by vladi-loco** [TypeStrong/atom-typescript#1304]

**Comment by guncha** [comment]
Is there an actual issue here?

**Comment by jonyeezs** [comment]
please just close this.... Is there anyone who is actually maintaining this repo?

**Comment by guncha** [comment]
@jonyeezs, me and my team use atom-typescript daily so if there are obvious issues, I usually fix them pretty quickly. There's no way I could keep up with all of the issues in the tracker so I'm not even trying. I haven't been good with reviewing PRs (because summer! and stellaris!) or working on new features, but it will change soon. So I guess the answer to your question is "sort of". If you're looking for some OSS experience, I'll gladly accept any help.

**Comment by jonyeezs** [comment]
@guncha thank you for responding!

I'm about to jump into TS. And would be using this library. I'll be glad to help atleast maintain the issues.

I'll be new to this, and just like you I have a day job too. But i think if we spread the load it would help.
