### ISSUE TITLE
Slow to process "projectInfo"

### ISSUE THREAD

**Issue by Goodwine** [TypeStrong/atom-typescript#1311]
The plugin has been running really slow lately and I wish to debug why it is, the behavior I see is that the counter at the bottom that indicates the actions that are running keeps going up, meaning that it's not completing anything, and it looks like it's stuck at `projectInfo` could you detail steps that I could follow to debug this problem to see if there is something wrong with my setup or if there is anything I could change on this plugin?

**Comment by guncha** [comment]
`projectInfo` can be pretty slow because it does a lot of work, but if it's hanging, there's clearly a problem. I've seen this before when Typescript has to do a lot of filesystem work due to misconfigured globs. Try to remove all `includes` and `excludes` options from the `tsconfig.json` and add the file you have open to the `files` array explicitly and see if that changes anything.

To debug further, since this is all happening in the Typescript compiler, you have to start the `tsserver` with a debugger and do some profiling or just stepping trough the code. To do that, there's a line in `client.ts` likes this:

```ts
const INSPECT_TSSERVER = false
```

If you change it to `true`, it will start the server with `node tsserver --inspect` and it will print a URL in the console that you can connect to with Chrome and and debug to your hearts content.

**Comment by Goodwine** [comment]
Thanks, I'll play around with this. I wonder if it would make sense to not block on "slow" commands so that "fast" commands like `completions` would run in parallel. Or does completions depend 100% on commands like projectInfo and quickInfo?

**Comment by guncha** [comment]
It's unavoidable. If `completions` is the first command after opening a file, it'll have to do the same amount of work as calling `projectInfo` would. There's also no concurrency in `tsserver` so all of the commands run one at a time. But like I said, `projectInfo` shouldn't take more than a few seconds so there's clearly some sort of issue here.

**Comment by Goodwine** [comment]
I'll close this issue, I'll debug my problems and reopen if I find anything useful. Thanks for your guidance!
