### ISSUE TITLE
[BUG] Import Name Constantly Misread

### ISSUE THREAD

**Issue by MrSnappingTurtle** [TypeStrong/atom-typescript#1332]
When importing modules, I often get a `...has no exported member...` error. When I hover over the module, it is looking for an odd spelling of the module:

![screen shot 2017-08-29 at 2 40 03 pm](https://user-images.githubusercontent.com/8148243/29845791-07f413a2-8cc9-11e7-9a53-83f343351809.png)

Notice it's looking for `MdToolbarModuleeludoM` instead of `MdToolbarModule`. Reopening the file fixes the issue.

**Comment by lierdakil** [comment]
Most likely related to #1333. See if updating to Atom 1.19.5 fixes it for you.

**Comment by MrSnappingTurtle** [comment]
@lierdakil I've updated to the latest. Still get the issue. Also, I noticed that it happens when I have two tabs open viewing the same file, if that's any help.

**Comment by lierdakil** [comment]
Yes, that helps. That would be the reason this happens probably.

/cc @guncha, I'm pretty sure this happens because we're creating `TypescriptBuffer` for each `TextEditor`, while multiple `TextEditor`s can share the same `TextBuffer`. Hence, we get duplicate change events. Properly addressing this would entail a pretty major rewrite, so I'm not entirely sure it's something I should do -- at least not without asking first.

**Comment by lierdakil** [comment]
Should be fixed in v12. Sorry about the long wait.
