### ISSUE TITLE
Does the package load in Atom 1.19+ ?

### ISSUE THREAD

**Issue by jimmytheneutrino** [TypeStrong/atom-typescript#1343]
I have been sitting on 10.x version of the package for some time but recently decided to try version 11.0.9.

It appears that it does not work at all. E.g., shortcuts do not work nor does autocompletion.
The only thing that appears after installing the package is the menu Packages->Typescript with 3 choices, none of which does anything.

There are no error logs.

I tried with Atom 1.19 and now also with Atom 1.20.

None of the 11.0.x version currently works but I do remember that I tried 11.0.x before (with an older version of Atom) and it did work.

The same ts project behaves well with atom-typescript 10.x or Visual Studio Code.

Is anyone else seeing this?

**Comment by anthony-pinskey** [comment]
I believe I experienced the same. Does syntax highlighting appear to be broken as well? It did not seem to work with my test Angular app.

**Comment by lierdakil** [comment]
atom-typescript<v11.0.7 is pretty broken on Atom 1.19+, and 11.0.7 should address precisely that. Note that v11.0.7 will refuse to start on Atom <1.19

I'm using latest on Atom 1.20 and see no problems that you describe. A thought that comes to mind that your Atom installation behaves like it's <1.19 for some reason (due to botched update or somesuch maybe?)

**Comment by jimmytheneutrino** [comment]
@anthony-pinskey Syntax highlighting is working (this is the only working thing).

I tried on a fresh system and it works. But still no lack trying to run on old (but updated) install of Atom. Maybe there is a conflict with some other package.

Anyway, if it does not affect anybody else, I think there's no use to investigate it in detail.
But let's maybe keep it open for a while.

**Comment by jimmytheneutrino** [comment]
It seems that the issue is with https://atom.io/packages/one-light-ui-adwaita instead.
It throws error on atom startup and somehow prevents atom-typescript from loading.

``` 
(in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at setLayoutMode (config.coffee [sm]:28)
    at Object.apply (config.coffee [sm]:1)
    at settings.coffee [sm]:2
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141)
    at theme-manager.coffee:284
```

**Comment by lierdakil** [comment]
Okay, so one of the reasons this might've happened in the first place is Atom now ships typescript grammar by default, which conflicted with our own. v12 ditches our grammar in favour of Atom's (because no reason to compete with something that ships by default) -- and that's the sole reason that's v12 and not v11.1 (because semver and backwards compatibility)

In any case, package loads happily on Atom 1.23 currently, so I'm going to close this.
