### ISSUE TITLE
f12 jump to deceleration not working in 11.0.9 

### ISSUE THREAD

**Issue by pete-hotchkiss** [TypeStrong/atom-typescript#1354]
This is an issue I see come up regularly when I upgrade. 

Hitting f12 to jump to a definition stops working completely. If I roll back to the last known version 11.0.3 then it starts working again.

Be nice to feel comfortable upgrading knowing features we're going to retain stability

**Comment by guncha** [comment]
If you open "Key Binding Resolver" panel and then put the cursor on the identifier and press F12, does it say that `f12` was pressed and that the `typescript:go-to-declaration` command ran?

**Comment by pete-hotchkiss** [comment]
sure does

![image](https://user-images.githubusercontent.com/16895748/31093259-0d2e768c-a7a9-11e7-8e4c-ef88473bd440.png)

**Comment by lierdakil** [comment]
Sorry about the silence. That is certainly very strange, especially considering the code responsible for the feature didn't change since 11.0.3 (sans formatting). I personally use the package a lot and `f12` works flawlessly.

Check developer console for errors (View -> Developer -> Toggle Developer Tools -> Console tab). Also, check that you're using the correct typescript grammar (there were some reports of conflicts with language-typescript -- this is "fixed" in v12 by removing our grammar altogether).

Last point, versions below v11.0.7 are most certainly broken with Atom 1.19 and above. The latest version of atom-typescript requires Atom v1.23.
