### ISSUE TITLE
Installing atom-typescript does not disable built-in language-typescript

### ISSUE THREAD

**Issue by dotmagic** [TypeStrong/atom-typescript#1374]
I installed atom-typescript and was suprised some features didn't work (for example auto import). The reason is there are 2 different kind of Typescript Syntax Highlights, build-in package `language-typescript` and `atom-typescript` (this one). I believe if a user install atom-typescript, language-typescript should be disabled, otherwise it becomes very confusing. Reference https://github.com/TypeStrong/atom-typescript/issues/549#issuecomment-325934841 and #1344

**Comment by lierdakil** [comment]
Well, that's certainly weird. And relatively recent. I haven't noticed that. Thanks for letting us know. 

Although, it's an open question whether we should disable built-in grammar. Maybe we should just drop our grammar and just use a built-in one. @guncha, any thoughts?

**Comment by taylon** [comment]
I just started using Typescript and my experience has been pretty bad because currently we have atom-typescript, atom-ide/typescript-ide and language-typescript.

I chose to use atom-ide which means that I don't get the snippets and grammar from atom-typescript (which are pretty good) and language-typescript is currently really really bad.

I think that having a high quality built-in grammar is the best way to provide a good experience for whoever is using typescript, no matter if the user is in atom-ide, atom-typescript or none the experience would be great.

So IMHO moving the grammar from this package to language-typescript would be ideal, I would be happy to make the pull requests if you guys think it is a good idea and would help.

**Comment by lierdakil** [comment]
Actually, it'd be rather hard for us to disable *any* package on installation, since we activate only when typescript grammar is used. Huh. This is a more difficult problem than I thought. Using Atom's bundled grammar seems more lucrative by the minute. @guncha, let me ask again: what do you think about dropping our grammar and using Atom's builtin instead?

**Comment by taylon** [comment]
I personally think that using the builtin grammar is the way to go, I don't see the reason for duplication specially because the grammar might be useful without atom-typescript, someone using atom-ide for example will use the builtin grammar and won't use atom-typescript.

Also the grammar for Typescript in Atom (both builtin and atom-typescript) is currently really really bad compared to VSCode for example. If we concentrate the grammar in one place we have the potential to deliver improvements for all atom users independently of whether or not they are using atom-typescript.

**Comment by lierdakil** [comment]
> someone using atom-ide 

That's just GUI. You still need backend, like atom-typescript or ide-typescript. So, irrelevant.

> grammar for Typescript in Atom (both builtin and atom-typescript) is currently really really bad compared to VSCode for example

Both our and builtin grammars are basically carbon copies of Microsoft's TypeScript grammar for TextMate. Until Atom supports other grammar models besides TextMate (which it hopefully will soon-ish, there has been some good work done on that), we're stuck with that.

**Comment by taylon** [comment]
> That's just GUI. You still need backend, like atom-typescript or ide-typescript. So, irrelevant.

I was obviously mentioning people using atom-ide with ide-typescript =D

> Both our and builtin grammars are basically carbon copies of Microsoft's TypeScript grammar for TextMate. Until Atom supports other grammar models besides TextMate (which it hopefully will soon-ish, there has been some good work done on that), we're stuck with that.

Makes sense, but my point is about the fact that today if we improve the builtin grammar by updating it from Microsoft's repo or like the PR I did a couple of days ago (https://github.com/atom/language-typescript/pull/13) atom-typescript users don't benefit.

**Comment by lierdakil** [comment]
So we're now (since v12) using the language-typescript package that ships with Atom. Thanks for your input everyone.
