### ISSUE TITLE
Syntax highlighting of method names

### ISSUE THREAD

**Issue by JNaftali** [TypeStrong/atom-typescript#1379]
it's borked. I think I found the problem in the grammar file - fixing it locally fixed the syntax highlighting, so that's good. I've submitted an issue/pull request (https://github.com/Microsoft/TypeScript-TmLanguage/pull/545) in the grammar repo. If/when that gets merged y'all might want to update.

EDIT: the more I look at this the less sure I am that I understand the problem. The proximal cause of the bad syntax highlighting seems to be that the names in method/function declarations are getting tagged with the CSS class of `entity` instead of `syntax--entity`. Similar problems occur anywhere the grammer file has `name: 'foo.bar.ts baz.bong.ts'` instead of `name: 'foo.bar.baz.bong.ts`

**Comment by JNaftali** [comment]
Actually... this issue might crop up in a couple places. Syntax highlighting also seems off for function declarations and examining the classnames on that element in the devtools it looks like it might be the same issue. If you do a regex search for `\.tsx?` in the grammars folder you'll find a total of 28 instances where the 'name' key of something is 'blah.bleh.ts bloh.bluh.ts' instead of 'blah.bleh.bloh.bluh.ts'. Making those changes seems to fix highlighting.

I've only a limited understanding of how grammar files, CSON, and syntax highlighting in Atom work, so the actual significance of all these things is kinda lost on me. But it's definitely true that syntax highlighting of some lines seems to be broken/inconsistent on certain parts of JS even when there's no actual typescript syntax there.

**Comment by lierdakil** [comment]
Hi. Thanks for the effort and sorry for the lack of response. We decided to discontinue our grammar in favour of what Atom bundles, see https://github.com/TypeStrong/atom-typescript/wiki/Grammar.

I was able to reproduce the issue using Atom's bundled TypeScript grammar.

It would seem that this issue is actually with https://github.com/atom/first-mate, since it doesn't seem to handle this syntax. But probably a good idea to create the issue on https://github.com/atom/language-typescript too, which I took the liberty of doing: https://github.com/atom/language-typescript/issues/16

I will close this as no longer relevant to this repo. Feel free to yell at me if you think I'm wrong.
