### ISSUE TITLE
False compile errors

### ISSUE THREAD

**Issue by akskos** [TypeStrong/atom-typescript#1386]
I'm running Atom 1.22.1 and atom-typescript 11.0.10. Often when I make changes to my code and save I get weird errors like `'=' expected.` for a line that says `export class PhotoController {` and `Cannot find name 'cttxxxx'.` for lines like `let body = ctx.body`. This happens especially when I copy paste code or type fast. The problem goes away with restarting atom. This kind of problem sounds like extremely slow computer but I'm developing with i7-5820k, ssd and plenty of free ram. 

Content of my tsconfig.json:
```
{
  "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "noImplicitAny": false,
      "removeComments": true,
      "preserveConstEnums": true,
      "sourceMap": true,
      "experimentalDecorators": true,
      "outDir": "build/"
  },
  "compileOnSave": true,
  "include": [
    "src/**/*"
  ]
}
```

**Comment by lierdakil** [comment]
Some of it can be related to https://github.com/TypeStrong/atom-typescript/issues/1332, which has been fixed in v12. There are probably other related heisenbugs lurking in the dark corners.

If you could confirm you can reproduce on v12 that would be nice. Thanks in advance (note: you need Atom v1.23 or above for v12 to even show up in available packages)

**Comment by lierdakil** [comment]
ETIMEDOUT
