### ISSUE TITLE
npm-shrinkwrap.json prevents registry mirrors from working

### ISSUE THREAD

**Issue by gera2ld** [TypeStrong/atom-typescript#1387]
`npm-shrinkwrap.json` has `resolved` fields, which make npm ignore the global `registry` config. As a result, we can hardly install this plugin behide a proxy. Can you remove that?

**Comment by gera2ld** [comment]
Solved by `apm config set shrinkwrap false`.

**Comment by lierdakil** [comment]
FWIW, I don't use shrinkwrap at [atom-haskell](https://github.com/atom-haskell) and didn't have any reports about newer incompatible dependencies crashing anything. Semantic versioning seems to work, more or less. [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus), which I also happen to (barely) maintain also didn't have any problems with that, not as far as I can remember at least. So throwing away shrinkwrap won't be a *huge* issue most likely, although I will admit it adds a bit of determinism into the chaos that is npm.

**Comment by guncha** [comment]
I've had it happen at work a few times (it's a PITA to debug) so now we're using Yarn for everything as well as deploying bundles with all of the dependencies built in. This is something that we can consider for `atom-typescript`:

1) The installation of the plugin will be considerably faster
1) The plugin gets to use the exact versions that it's tested with (this is a pro and a con in case of security updates, but I'm not aware of any instance where that could have been an issue)
1) The node_modules aren't shared between packages anyway AFAIK

I think nr 1 makes the more complicated build process worth it.

**Comment by lierdakil** [comment]
> The installation of the plugin will be considerably faster

It only takes a minute or so. I don't think anyone cares. I think it only applies to initial installation, not updates, see below.

> The plugin gets to use the exact versions that it's tested with 

That would be relevant if we had some spec coverage. At the moment, we have none. So "tested" is a bit of a strong word.

> The node_modules aren't shared between packages anyway AFAIK

They aren't. But I'm pretty sure `node_modules` aren't wiped on package updates, so making a monolithic bundle will make updates considerably larger (because, come on, tsc isn't exactly small), and arguably slower (depending on Internet connection)

Frankly, I'm not a big fan of this idea.

**Comment by guncha** [comment]
We do get reports of dependencies not being updated together with the main package due to NPM being, as you kindly put it, chaos. Also, "testing" doesn't just refer to automated testing so it's relevant here.

I just looked at the size of node_modules for this plugin and it's 37MB! WAT? 27MB of that is Typescript and about half of that are unused Javascript bundles like `typescript.js`, `typescriptServices.js`, etc. as well as unused `.d.ts` files.

I really hope Atom package updates don't just download it all over again, but after just seeing Atom download 200mb to update itself, I'm doubtful.

We could probably shrink the package down to under 1 MB compressed and minified, but yeah, is it worth it?

**Comment by lierdakil** [comment]
> We could probably shrink the package down to under 1 MB compressed and minified

I sincerely doubt that we could, to be honest. We do have to bring typescript with us because we want to be able to run tsserver if there isn't one available in current project or in path. And I doubt it could be compressed into several megs, let alone one. But maybe I'm wrong? Anyway, I find that at the moment, better uses of our time are available, e.g. #1332 (I'm sure there were a few other reports of the same issue, but I couldn't find those right away)
