### ISSUE TITLE
Can't detect tsconfig.json!!

### ISSUE THREAD

**Issue by LoganDark** [TypeStrong/atom-typescript#1394]
No matter what I try to do, this plugin just absolutely refuses to load the tsconfig.json. Here's my project:
![image](https://user-images.githubusercontent.com/4723091/34975701-e3dbf4ac-fa47-11e7-8be4-d48cff20fcfe.png)
It's on a remote volume (samba). It seems to work fine on my local volume, but I'm not working on my local volume!

**Comment by lierdakil** [comment]
> This is unacceptable.

Sorry to be frank, but we're not on your payroll for it to be "acceptable" or "unacceptable". I understand your frustration, but your approach doesn't motivate to help you. Quite the opposite, in fact -- the kneejerk reaction is to say "use another package" or "switch to vscode" and be done with it.

> Why is there no way to manually load a tsconfig?

I'm not sure you yourself understand exactly what you're asking here. I certainly don't. But the universal answer to a "Why is there no X?" question would be "Because nobody bothered to implement that yet, pull requests are welcome".

---

Explain your setup in more detail, and maybe we can figure something out. Or just don't use our package, as I said, there are alternatives available.

Some questions to get you started:

- What OS are you using?
- What version of TypeScript are you using?
- How do you connect to your "remote volume"?
- How does "refusal to load tsconfig" manifest? I.e. what doesn't work, exactly?

**Comment by LoganDark** [comment]
By "this is unacceptable", I wasn't trying to be rude, or demand you fix it, or anything like that. I was simply saying just that: it's unacceptable. In fact, you are absolutely correct - "the kneejerk reaction is to say "use another package" or "switch to vscode" and be done with it." And that's exactly what I will do if this doesn't get fixed.

---

To answer your questions:
> What OS are you using?

macOS 10.13.2.
> What version of TypeScript are you using?

The latest? The package version is 12.0.0.
> How do you connect to your "remote volume"?

Samba. Using "connect to server" (command-K) in finder.
> How does "refusal to load tsconfig" manifest? I.e. what doesn't work, exactly?

![image](https://user-images.githubusercontent.com/4723091/34983567-dd8b4f42-fa62-11e7-86d5-428875382fd2.png)
![image](https://user-images.githubusercontent.com/4723091/34983576-e3157d3e-fa62-11e7-8d6b-3366e10b0606.png)
Refusal to load tsconfig. Simple as that.

**Comment by lierdakil** [comment]
> Refusal to load tsconfig. Simple as that.

There can be other reasons for observed behaviour, actually. One relatively common reason is flaky `include` or `exclude` in `tsconfig.json` itself. To avoid pointless wild goose chases, could you check that your sources are *indeed* included and *not* excluded in tsconfig?

> The latest? The package version is 12.0.0.

Based on your answer I will assume "bundled". But just FYI, the package will use whatever typescript it can find in `node_modules` or anywhere in `NODE_PATH`.

> macOS 10.13.2.

That's inconvenient for both of us because I only have a passing knowledge of macOS. Expect dumb questions. Also can't run any tests on my own because I don't have a spare Mac lying around.

> Using "connect to server" (command-K) in finder.

That... actually doesn't tell me a whole lot, sorry to say. But maybe I can ask a more specific question: is samba remote mounted somewhere on the local filesystem? (i.e. can, say, bash/zsh access it directly?). Also, to be clear, are your sources also on that remote, or somewhere else?

**Comment by LoganDark** [comment]
> There can be other reasons for observed behaviour, actually. One relatively common reason is flaky `include` or `exclude` in `tsconfig.json` itself. To avoid pointless wild goose chases, could you check that your sources are _indeed_ included and _not_ excluded in tsconfig?

Stop right there. My `tsconfig.json` is 100% valid, and widely used and tested by countless others.

> Expect dumb questions.

Okay.

> is samba remote mounted somewhere on the local filesystem?

Of course.

> are your sources also on that remote?

They're literally in the same project folder. Every single file referenced by tsconfig and the TypeScript files are in the same exact folder. And that folder is on the remote, yes.

**Comment by LoganDark** [comment]
I copied the project folder to my local filesystem (not the remote Samba one), and it still can't find the tsconfig. What is going on here?
![image](https://user-images.githubusercontent.com/4723091/34990078-a0e3e4ac-fa79-11e7-845e-55e15d9ea445.png)

**Comment by lierdakil** [comment]
> My tsconfig.json is 100% valid, and widely used and tested by countless others.

A dangerous assumption. For one, the fact that it's used and tested by "countless others" doesn't mean it's valid for your specific set-up.

Well, at least the samba remote seems unrelated, which is something of a relief for me personally since it suggests that the issue isn't OSX-specific and local tests are a possibility.

If it's not under NDA or something similar (no idea why `tsconfig.json` would be, but you never know), could you perhaps just post it somewhere (pastebin, gist, etc)? Alternatively, get TypeScript 2.6.2 (for instance, definitely 2.2 or above) and run `tsc --project ./` in the directory with `tsconfig.json`, see what it says -- quite possible it'll complain about *something*.

**Comment by LoganDark** [comment]
Where do I find `tsc`? It doesn't seem to be in my `PATH`.

**Comment by lierdakil** [comment]
The easiest way is to `npm install tsc` I guess. If you have `npm` that is. And if you don't... well, usually you'd want to.

Alternatively, typescript is bundled with the package, so you can find `tsc` in `$ATOM_HOME/packages/atom-typescript/node_modules/typescript/bin/tsc`, but I have no idea where `$ATOM_HOME` is on OSX -- there's a chance it's just `$HOME/.atom`, but don't quote me on that.

**Comment by LoganDark** [comment]
Yeah, I have `npm`. And you forgot a `-g`, I think. And you also forgot that `tsc` is deprecated in favor of `typescript`.

```
0 LoganDark ~/Desktop/JScripting tsc --project .
error TS18003: No inputs were found in config file '/Users/LoganDark/Desktop/JScripting/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["./"]'.
```

I'm assuming that's my problem and there's nothing wrong with `atom-typescript`...?

**Comment by LoganDark** [comment]
I don't think `filesGlob` is supported officially by atom-typescript.

**Comment by lierdakil** [comment]
> And you forgot a -g, I think

Not necessarily, no. I personally despise global installs.

> And you also forgot that tsc is deprecated in favor of typescript.

Sorry, my mistake.

> I'm assuming that's my problem and there's nothing wrong with atom-typescript...?

Apparently, yes. `exclude` takes precedence over `include`, actually. So it would seem you're basically excluding everything.

> I don't think filesGlob is supported officially by atom-typescript.

That's been thrown away since TS 2.2, due to TS compiler supporting globs natively now. If you point me to where you found reference `filesGlob`, I'll try to update that.

**Comment by LoganDark** [comment]
> Apparently, yes. exclude takes precedence over include, actually. So it would seem you're basically excluding everything.

No I'm not. But I might not be including anything. Look at the screenshot below.
> If you point me to where you found reference `filesGlob`

In my tsconfig.
![image](https://user-images.githubusercontent.com/4723091/34991744-8b5d63c8-fa7f-11e7-9f0b-2962b1ce2039.png)
If I change `filesGlob` to `include`, do you think it'll work?

**Comment by LoganDark** [comment]
Nope.
![image](https://user-images.githubusercontent.com/4723091/34991790-c4e83bc2-fa7f-11e7-8db7-1c1929cf1482.png)

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/34991828-ef28c870-fa7f-11e7-80f1-cc5a1ffc7ad5.png)
Oh hey, it works. No issue with `atom-typescript` here.

**Comment by lierdakil** [comment]
Welp, we could've both saved 3 hours if you did as I said and checked your tsconfig for `include` and `exclude`, as [I suggested](https://github.com/TypeStrong/atom-typescript/issues/1394#issuecomment-357924521).

Glad to hear you solved it.

**Comment by LoganDark** [comment]
I thought `filesGlob` would've handled that. Guess not.

**Comment by lierdakil** [comment]
In case you're wondering, `filesGlob` was a hack used by `atom-typescript` back in the early days of TS 1.x, when `tsconfig.json` required *all* project files be enumerated explicitly in `files` attribute. It's not a thing since `atom-typescript` v11, when it was thrown away (together with a lot of other stuff) in an effort to keep this package maintainable.
