### ISSUE TITLE
Tooltip gets stuck

### ISSUE THREAD

**Issue by guilhermevrs** [TypeStrong/atom-typescript#1412]
Hi,

We are facing some weird issues with the tooltip on hover.

Sometimes, when your mouse hover an object and you scroll or change tab, the tooltip shows up and gets stuck on it.
Example:

![2018-03-07_09-54-08](https://user-images.githubusercontent.com/1570567/37082882-07cb1848-21ee-11e8-90bb-09c2051a3b48.gif)

We can get the tooltip to disappear sometimes when returning to the correct tab where it was generated. But it's not a silver bullet solution, sometimes it does not want to go away.
The only way is to actually restart atom.

When we disable the atom-typescript plugin, the tooltip disappears. But after re-enabling it, the tooltip come again to the same position.

I have tried to reproduce a couple of times and noticed that on the console, you get errors like:

Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\dev\null\inferredProject1*'

where the number in the end gets incremented every time a new occurence of the error happens.

OS: Windows
Atom: 1.24.0
Atom-typescript: 12.3.3

**Comment by andyrichardson** [comment]
Thanks for the suggestion, I have also encountered this issue.

It might be worth mentioning that `ctrl+shift+f5` can be used to quickly restart the editor.

**Comment by lierdakil** [comment]
I have occasionally observed similar behaviour, but could never reproduce it.

> Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\dev\null\inferredProject1*'

A stack trace would be very helpful.

**Comment by guilhermevrs** [comment]
Unfortunately the console does not log any stack trace, otherwise I would have posted :(

I haven't had enough time to dive into the code and debug it (now that I can reproduce systematically).

Quickly looking, the problem may be related to this method https://github.com/TypeStrong/atom-typescript/blob/db69edd8d92d6602d07f5938c0fbf06659566497/lib/main/atom/tooltipManager.ts#L95

What do you guys think?

If you point me out some basis, I can try to put some breakpoints and see what it's going on

**Comment by lierdakil** [comment]
> If you point me out some basis, I can try to put some breakpoints and see what it's going on

Well, I think it's clear that some kind of race condition is going on, and looking at the code closely, there aren't that many places where it could be. The only meaningful `async` function being `showExpressionType`, and the only meaningful (i.e. not usually resolved straight away) `await` there being here:
https://github.com/TypeStrong/atom-typescript/blob/1dca06aee3fa13e79d95cb073d3bb44cef22f384/lib/main/atom/tooltipManager.ts#L132 

This is pure speculation, but I would expect something like this is happening:

1. `showExpressionType` is triggered on timeout
2. `showExpressionType` `await`s on `quickinfo`
3. Active editor changes
4. `quickinfo` resolves
5. The tooltip for a previously active editor is shown

I guess this could be solved by a boolean flag, but that's ugly. Sadly, promises aren't cancellable.

The problem is exacerbated by an architectural flaw where each editor has its own tooltip (which is in hindsight an obvious mistake since there's no "valid" way to get multiple tooltips)

... anyway, 12.3.4 fixes the architectural flaw, which should help somewhat. Tooltip might still get "stuck", on occasion, but it should "unstuck" itself once mouse moves over any typescript editor. I'll try to figure out a more permanent solution, but I hope this will do until then.

**Comment by lierdakil** [comment]
Please open new issues if something similar happens after v12.4.0
