### ISSUE TITLE
Error: Cannot write file 'xyz.js' because it would overwrite input file

### ISSUE THREAD

**Issue by alexlawrence** [TypeStrong/atom-typescript#1484]
In a project with a tsconfig.json, many TS files and some JavaScript files I get an error for each JS file in the project. The error messages states: "Cannot write file 'xyz.js' because it would overwrite input file".

Following the advice of this link helps: https://tutel.me/c/programming/questions/40460790/getting+a+storm+of+quoterror+ts5055+quot+messages+on+every+typescript+compile+in+vs+code However, I have no idea regarding the cause of it or the implications of the solutions.

Do you have any idea what is happening here?
Thanks!

**Comment by lierdakil** [comment]
The crux of the issue is perfectly explained in the link you've provided. I really have no idea why are you asking about that here.

Anyway, here's a TL;DR. TypeScript will try to compile the file (either on save if `compileOnSave` is enabled, or on `typescript:build`). By default, TypeScript compiler will output the compiled file using the same name and path as the source file, but with `js` extension. This obviously creates issues when the source file itself has `js` extension. TypeScript compiler will refuse to overwrite the source file by the compiled output (thankfully). Specifying the `outDir` tells TypeScript compiler to put compiled files under a different path than source files, which fixes this conflict.

For reference, this is a generic TypeScript question. This bugtracker is not a generic TypeScript support forum. Asking on StackOverflow or somesuch will generally yield better results.

Cheers!

**Comment by alexlawrence** [comment]
Thanks for your explanation! I completely agree with you there. I did not want to bother you with a generic TypeScript question. Also, thank you for working on this plugin!

My original question was missing some context. The TypeScript compilation in the project I am getting these errors, which runs as part of a build, works without any errors. I am getting these errors only reported within Atom, presumably from atom-typescript. This is why I thought it belonged here.
