### ISSUE TITLE
Auto import suggests long node_modules path instead of just the package name

### ISSUE THREAD

**Issue by ukaaa** [TypeStrong/atom-typescript#1489]
For some time now, whenever I add a node module import, e.g. `Observable`, and I do CTRL+Enter to show intentions, it suggests to import it from `../../node_modules/rxjs`. But what I actually want is that it simply suggests to import it from `rxjs`. 

Any idea what caused a change in the intentions? Is it a local setting? It's so annoying.

**Comment by lierdakil** [comment]
Hi. Sorry for the prolonged silence. Import suggestions are given to us by the TypeScript server, so the first thing to check would be your `tsconfig.json`. Also, check your TypeScript version -- it *might* be a bug that has since been fixed.

If you can't pinpoint the issue, try to construct a more or less minimal testcase. FWIW, I did not notice anything like this going on with my projects.

**Comment by ukaaa** [comment]
Sorry for the even longer prolonged silence. I have taken some time to investigate and updating to Typescript 3 seems to have fixed the suggested import paths.
