### ISSUE TITLE
Autocomplete for imports not always working

### ISSUE THREAD

**Issue by surdu** [TypeStrong/atom-typescript#1490]
![autocomplete](https://user-images.githubusercontent.com/11520795/52859671-fb42d680-3135-11e9-8fc8-a963819c7f94.gif)

In the above video, every time the autocomplete disappears I press enter. That being said, the only time it works is if I add a space and then delete it. This happens only for imports autocomplete as far as I can tell ...

I've checked the key binding resolver and it seems the autocomplete-plus correctly receives the key:
![screen shot 2019-02-15 at 15 28 35](https://user-images.githubusercontent.com/11520795/52859880-98057400-3136-11e9-9b20-d9dd5955be98.png)

Considering the specific case of this issue, is there any chance this could be a bug with atom-typescript and not autocomplete-plus ?

**Comment by lierdakil** [comment]
Well, I can't reproduce this. One thing to try is to check whether this happens only with `enter` or with other keys as well (`tab` for instance -- which can also be used to confirm autocompletion by default). If this only happens with `enter`, that's definitely not an Atom-TypeScript problem (and most likely something *does* steal the keypress after all). Otherwise, it's honestly 50/50, a careful study of the debug output might be required; setting `window.atom_typescript_debug` to a truthy value (e.g. `true` or `1`) will enable dumping a lot of information into the dev console. The first thing to look at is the completion list reported by the server.

**Comment by surdu** [comment]
If I use tab is the same.

As for the response for `completionEntryDetails`, is an empty array.

**Comment by lierdakil** [comment]
The primary completion data is sent in response to `completionInfo` command -- look at that one first (share a snippet if possible). `completionEntryDetails` is just for bells and whistles, it doesn't really affect core functionality (or at least it shouldn't) -- although the fact that it's empty is worrying, it really shouldn't be.

**Comment by surdu** [comment]
There is no `completion` request in the case where it's not working:

<img width="564" alt="screen shot 2019-02-17 at 02 13 39" src="https://user-images.githubusercontent.com/11520795/52906690-af894d80-3259-11e9-8866-ca8741d25a89.png">

**Comment by lierdakil** [comment]
Huh. You're still on TypeScript v2.x I take it?

Are you positive that there is 1:1 correlation here? That is, if there was a "completions" command, then it works as expected, otherwise it does not? There's a little bit of caching going on in the background for performance reasons, the intention is to avoid issuing the same completion request multiple times (FWIW, the code has been there since v11.0 IIRC, and this is the first bug report related to that code path)

**Comment by surdu** [comment]
Yes, the project uses typescript 2.7.2.

Myeah, apparently there is no correlation... In the sense that it can work even when no 'completion' request is made.

That being said, as requested above, here is the response of the `completions` request:
<img width="663" alt="screen shot 2019-02-17 at 02 42 36" src="https://user-images.githubusercontent.com/11520795/52906853-f5e0ab80-325d-11e9-86d6-6d6edf0e396b.png">

**Comment by lierdakil** [comment]
I'll try to repro on TS 2.7.2 and get back to you. To be clear, are you using Atom v1.34.0, or an earlier version?

**Comment by surdu** [comment]
Sorry 😞, I should have started with this ...

|Soft|Version|
|-----|------------|
|atom| 1.35.0-beta0|
|autocomplete-plus| 2.42.0|
|atom-typescript| 13.1.0|
|os|macOS Sierra 10.12.6 (16G1710)|

Do you need versions for anything else ?

Also, if you could point me to the code that's responsible for that autocomplete, I could at least try to debug it myself, if not also fix it 😃

**Comment by lierdakil** [comment]
The bulk of the code responsible is in https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/autoCompleteProvider.ts

**Comment by lierdakil** [comment]
So, I didn't manage to reproduce the exact bug you're describing, but I did manage to find a few annoying bugs related to autocompletion that might have the same underlying cause. Long story short, apparently there is a race condition related to how changes are pushed to tsserver and autocompletion requests are made. If I'm right with this hunch, the bottom line should be that it's *really* hard to trigger the behaviour you're describing here when completion is triggered manually (i.e. by cmd+space or another explicit keybinding, as opposed to being triggered by a text change). To be fair, the current code uses a dirty, dirty hack to force-push updates to tsserver (the initial justification for that is the fact that pushing changes *too* eagerly can have a non-negligible performance impact on Atom UI, so we push changes asynchronously, but force-push those if we need to, which is, let's face it, *really often*), so it's not a surprise that it apparently started misbehaving.

Anyhow, I've changed the way that text buffer updates are tracked in the `synchronous-change-tracker` branch here (also #1491). You seem to know your way around stuff, so if it's not too much trouble, could you perhaps test it to see if this branch fixes your particular problem? Thanks in advance.

Just in case, a short how-to: 

1. Uninstall atom-typescript from Atom (`apm uninstall atom-typescript`)
2. Clone the repo (`git clone https://github.com/TypeStrong/atom-typescript`)
3. Check out the branch `synchronous-change-tracker` (`git checkout synchronous-change-tracker`)
4. Run `apm install` and `apm link` in the repo root dir.
5. Restart all running Atom instances (if any)

**NOTICE** since you're using Atom beta version, you might need to use `apm-beta` instead of `apm`. I'm not *entirely* sure how that works on OSX.

**Comment by surdu** [comment]
Unfortunately, my issue still reproduces 😞

**Comment by surdu** [comment]
I didn't encountered this issue in a while now ... I'm guessing it was solved with one of the updates.

Thank you very much for the remarcable support into figuring out this issue! Much appreciated!

**Comment by lierdakil** [comment]
Just to clarify, are you using the fork I asked you to test in my previous comment, or are you on the mainline releases?

**Comment by surdu** [comment]
Mainline release
