### ISSUE TITLE
I keep getting TS linting issues when working on JS file

### ISSUE THREAD

**Issue by webMasterMrBin** [TypeStrong/atom-typescript#1492]
![image](https://user-images.githubusercontent.com/25171709/53709818-3141c380-3e75-11e9-9a37-dc0b82e1254d.png)

ts warning info in .js file?  how to disabled

**Comment by lierdakil** [comment]
Unless you have 
![image](https://user-images.githubusercontent.com/7275622/54196583-d5a9b280-44d2-11e9-9a3d-e3d42632ac21.png)
enabled in Atom-TypeScript settings, it will straight up ignore JavaScript files.

So. Either you have that option enabled, and since it's disabled by default, it's not clear what's your issue exactly.

Or it's not actually atom-typescript, but something else. Notice you may need to restart Atom after disabling some packages (like ide-typescript for instance) for them to _really_ be disabled -- cleaning up after a package is disabled can be tricky and it's often overlooked.

**Comment by lierdakil** [comment]
Closing due to age.
