### ISSUE TITLE
Type checking on unsaved files

### ISSUE THREAD

**Issue by martpie** [TypeStrong/atom-typescript#1495]
There is one thing supported out of the box by VS Code that I really miss in Atom: the ability to `cmd+N`, then select the language of the document to TypeScript, and start hacking:

- on Code, TypeScript will be already loaded, so you can see type errors
- on Atom, no checks are performed

<img width="1552" alt="Screen Shot 2019-03-25 at 11 02 28" src="https://user-images.githubusercontent.com/1311607/54910972-b442c080-4eed-11e9-9c1d-ea73c8f297ba.png">

<img width="1552" alt="Screen Shot 2019-03-25 at 11 02 38" src="https://user-images.githubusercontent.com/1311607/54910971-b442c080-4eed-11e9-8b75-427204b25073.png">

I have no idea if this is actually do-able with Atom's APIs, and I did not see any matching issue on this repo, but supporting this usecase would be awesome.

**Comment by lierdakil** [comment]
Hi. There are a couple challenges with the new files. For one, those don't have any meaningful file path. Atom-TypeScript actually checks if the editor has a well-defined file path (and it also checks file extension to avoid undue weirdness if TypeScript grammar was selected accidentally), since that file path is then used to relate the file to the correct project and whatnot. Consequently, I doubt unnamed files would work as well as we'd like even if I did disable this check.

One recommendation I can make though, try using [Advanced Open File](https://atom.io/packages/advanced-open-file) package for Atom. It allows you to not only create & save new files faster (well, -ish), but it also sets file path for newly-created files, which will work around this issue.
