### ISSUE TITLE
Rename refactoring updates node_module files

### ISSUE THREAD

**Issue by nelson6e65** [TypeStrong/atom-typescript#1504]
Hi. When I do use to `Rename Variable` (F2) in a `import`, it also renames declarations under vendor files (`node_module/`). This should be avoided, the modification of vendor/external files.

### Reproduction
I used `F2` in my migration of classes, for uses inside my project file. Ex:

```ts
import { IonModule } from '@ionic/angular';
```

To

```ts
import { IonicModule } from '@ionic/angular';
```

Then, definitions under `node_modules/@ionic/` changed too.

### Recommendation
Use the `exclude` option in the `tsconfig.json` file. 

```json
{
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by lierdakil** [comment]
Hi. This is not an issue with Atom-TypeScript, and frankly not an issue at all, since `node_modules` doesn't necessarily have a special meaning depending on context. That said, your recommendation is great, so I've [added it to the FAQ](https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#rename-refactor-updates-files-in-node_modules). Thanks.
