### ISSUE TITLE
Deleting a tsconfig.json file should clear it from out hot cache

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#151]
Currently you need to hard reload atom.

**Comment by csnover** [comment]
Does this fix all things, not just tsconfig.json? I’ve been having a painful time dealing with outdated caching, usually due to switching from one branch to another. Atom generally figures out what’s happened eventually but atom-typescript doesn’t. It looks like this code is maybe generic enough but I’m too tired to read straight, so… #lazyweb question :).

**Comment by basarat** [comment]
> Does this fix all things, not just tsconfig.json

No. We don't have any file watching for .ts files. So:

* if you open file `modFoo/a.ts`. This will load the ts file + tsconfig for this file and keep it in memory. 
* close file (we have this file in cache now) 
* change branch.
* open file `modFoo/b.ts` .... we will still have an outdated version of `a.ts` in memory, so your intellisence about stuff in `a.ts` will be wrong. This will resolve itself once you reopen `a.ts`. 

TSServer should help here :heart:
