### ISSUE TITLE
can't find .json in project file list despite tsc ok

### ISSUE THREAD

**Issue by jfellus** [TypeStrong/atom-typescript#1512]
I have a monorepo with the following hierarchy :

/tsconfig.json
/src/stuff.ts
/packages/adapters/tsconfig.json
/packages/adapters/src/stuff.ts
/packages/adapters/src/files/blabla.json

blabla.json is imported in some ts modules inside the adapters package. 

/packages/adapters/tsconfig.json extends 
/tsconfig.json

running `tsc --build` in *any* meaningful folder yields **no error**. Great !

but in atom I get 
`blabla.json is not in project file list. Projects must list all files ...`

my blabla.json is properly included in /packages/adapters/tsconfig.json

````json
/* /packages/adapters/tsconfig.json */
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "./lib",
    "rootDir": "./src",
    "composite": true
  },
  "include": ["./src/", "./src/files/*.json"]
}

/* /tsconfig.json */
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "composite": true,
    "removeComments": true,
    "strict": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "baseUrl": "./",
    "paths": {
      "@blabla/adapters": ["./packages/adapters/src"],
    },
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
  },
  "exclude": ["node_modules", "**/*.spec.ts", "**/lib"]
}

````

should I set any option on the atom plugin to finally get the same behavior as a direct `npx tsc --build` ?

thanks !

**Comment by lierdakil** [comment]
Hi. Thanks for your report. Initial investigation suggest that this is probably an upstream problem, but I couldn't find a corresponding upstream issue during a cursory search.

The issue does not manifest if `/packages/adapters/tsconfig.json` is using `files` instead of `include`, but that's not a solution of course.

The issue only manifests on `composite: true` projects.

`extends: ...` doesn't affect the issue.

I have a vague suspicion that https://github.com/microsoft/TypeScript/pull/27844 might have missed something in the tsserver code.

There are reports of this happening in VS Code (f.ex. https://github.com/TypeStrong/ts-loader/issues/905#issuecomment-465253989). Not sure how up-to-date those are though.

As a workaround, you can add `6307` to 'Ignore Diagnostics' package setting -- that will suppress the error message. As far as I can tell, it affects nothing else.

**Comment by lierdakil** [comment]
I've created an upstream issue with minimal repro. Hopefully they fix it eventually. https://github.com/microsoft/TypeScript/issues/33827

**Comment by jfellus** [comment]
thanks a lot !
ignoring will make it for me
Still interested in knowing if its a bug on TSServer side ;-)

**Comment by lierdakil** [comment]
Issue reportedly fixed upstream, this should eventually find its way into TypeScript 3.7.something release. 3.7.1 if we're lucky. I think it's safe to close this.

**Comment by nscozzaro** [comment]
I'm still getting this problem, in PyCharm with TypeScript version 3.7.3

![image](https://user-images.githubusercontent.com/15185105/70462981-ffa3fb80-1a89-11ea-88dc-e6a3b4d28d51.png)

**Comment by lierdakil** [comment]
@nscozzaro so...
>PyCharm

Why are you reporting this here again?

But yeah, the upstream fix is still unpublished as of yet. It's in `master` branch, but apparently didn't get into `release-3.7` branch. You can pester upstream if you think it should.
