### ISSUE TITLE
Autocomplete for class member variables buggy

### ISSUE THREAD

**Issue by mohitatray** [TypeStrong/atom-typescript#1532]
I am new to atom. Just installed this package with atom-ide-ui. Installed it for working with angular with typescript.
I noticed a bug in autocomplete. For an example let's create a class Abc --
```
export class Abc {
    size: number

    getSize(): number {
         
    }
}
```
When I type `siz` inside the getSize() method, I get the autocomplete suggestion `size`. But when I press enter, it gets autocompleted to `sizthis.size` instead of `this.size`.

**Expected behaviour**: Auto-complete should replace `siz` with `this.size`
**Actual behaviour**: Auto-complete doesn't replace `siz` but adds/cocats `this.size` after it resulting in `sizthis.size`

The same happens for `extends` keyword too sometimes.
I am using atom in Ubuntu 19.10

**Comment by lierdakil** [comment]
Thanks for reporting!

This was introduced in v13.4.1. Should be fixed in v13.4.7 (along with a few other autocompletion issues) 

Autocompletion logic was changed quite a bit recently, so there might be some edge cases that are still not handled entirely correctly. Please don't hesitate to open new issues if something else doesn't quite work.
