### ISSUE TITLE
Support for optional chaining?

### ISSUE THREAD

**Issue by ramtinsoltani** [TypeStrong/atom-typescript#1536]
According to the [change log](https://github.com/TypeStrong/atom-typescript/blob/master/CHANGELOG.md#1340) TypeScript 3.7 is bundled. Are all new features of 3.7 supported?

I'm trying to use [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and get `Expression expected` error.

Atom TypeScript: 13.4.8
TypeScript: 3.7.4
Atom: 1.42.0 x64
OS: macOS Catalina 10.15.2

**Comment by lierdakil** [comment]
Remember that Atom-TypeScript will use whatever TypeScript installation it can find in the project's `node_modules`, and will only default to the bundled version if it can't find any. It reports which version it's currently using in the status bar, e.g.
![image](https://user-images.githubusercontent.com/7275622/72204861-808d5300-348d-11ea-962d-70ed68bd4a85.png)

Also, be aware that you likely need to restart Atom after updating TypeScript for it to pick up on the new version.

FWIW, everything works exactly as expected on my end:
![image](https://user-images.githubusercontent.com/7275622/72204907-f4c7f680-348d-11ea-831e-ef35221c91f6.png)

**Comment by mzarandona-bw** [comment]
Same issue for me.

Atom TypeScript: `13.4.8`
TypeScript: `3.7.2`
Atom: `1.42.0 x64`
OS: `macOS 10.15.1`

**Comment by ramtinsoltani** [comment]
<img width="693" alt="Screen Shot 2020-01-13 at 11 51 48 AM" src="https://user-images.githubusercontent.com/7918069/72287045-332ef400-35fb-11ea-9273-02dff7ccc502.png">

As you see, the picked up version is 3.7.4 and the issue still persists. Are there any compiler options I should provide in `tsconfig.json`?

**Comment by lierdakil** [comment]
Please share `apm list` output, just to make sure we're not hunting ghosts. One particular thing to look out for is `ide-typescript` package being installed and enabled, because it does not support optional chaining, and will report it as error, and it also calls itself "typescript" in the IDE interface.

In case it's not some other package interfering, here's a minimal project that optional chaining should (i.e. it does on my end) work with: https://gist.github.com/lierdakil/d60962913651781250f7312b497d144a (you can `git clone` this URL).

**Comment by ramtinsoltani** [comment]
`ide-typescript` was the actual problem!

Disabled the package, restarted Atom, and it's working now. Thanks for the help.
