### ISSUE TITLE
(Re-) add keyboard shortcut for type info

### ISSUE THREAD

**Issue by andb0t** [TypeStrong/atom-typescript#1543]
It would be great to disable the "on-hover" trigger for the type info and use a key combination instead.  Currently, the type and linter info fight for space on the screen, which one could solve by having the option for assigning a keyboard shortcut to type info instead of hovering.

I see some related issuesis closed, but the problem isn't fixed in the current version. Those are the related issues:

*    #726
*    #957
*    #1267

This seems to have been a feature in a previous release and somehow was lost during a rewrite. Is there something planned?

**Comment by lierdakil** [comment]
Keyboard shortcut was re-added in v12.0.0 back in the end of 2017 (specifically in https://github.com/TypeStrong/atom-typescript/commit/48ce42c34bf6de6afb6b0f89db79ffea56150bc5). Which is exactly why #957 was closed.

For keyboard-activated tooltips, bind a shortcut you like to `typescript:show-tooltip` function. See https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings for more information on customizing key bindings. It's recommended to add the key binding to `atom-text-editor`, since the command is editor-bound. If you want a more specific selector, use `atom-text-editor:not([mini]).typescript-editor` which will only trigger on editors managed by atom-typescript. Perhaps this should be added to the FAQ.

If you want to "disable" tooltips on hover, the easy way to do this is by setting tooltip delay to a very high value (`86400000` for instance is a delay of 24 hours, which should be reasonably large for tooltips to never appear at all). If you're using built-in tooltips (the baby blue ones -- or whatever colour the generic tooltips are in your ui theme), then adjust "Type tooltip delay" setting in atom-typescript settings accordingly. With atom-ide-ui, you can find similar option in atom-ide-ui settings under "Datatips".

**Comment by andb0t** [comment]
Thanks for the quick answer! That's a good workaround, works perfectly. I guess that should go to the FAQ to prevent ppl like me asking that in future ;)

**Comment by lierdakil** [comment]
Okay, I've [updated the FAQ](https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-want-to-use-the-keyboard-to-control-type-tooltips-instead-of-hovering-the-mouse). Feel free to suggest edits if something seems off.

**Comment by andb0t** [comment]
That's perfect, should be clear for everyone
