### ISSUE TITLE
Atom-Typescript error: terminated on signal: SIGSEGV

### ISSUE THREAD

**Issue by jaqmol** [TypeStrong/atom-typescript#1545]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.5.1

### Stack Trace

Atom-Typescript error: terminated on signal: SIGSEGV

```
At Error: terminated on signal: SIGSEGV

Error: terminated on signal: SIGSEGV
    at ChildProcess.cp.once (/packages/atom-typescript/dist/client/client.js:160:19)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  3x -2:14.5.0 core:move-down (input.hidden-input)
     -2:13.7.0 core:save (input.hidden-input)
  4x -1:07.1.0 core:copy (input.hidden-input)
     -1:05.1.0 core:save (input.hidden-input)
  4x -1:04.7.0 core:close (input.hidden-input)
     -0:53.4.0 autocomplete-plus:confirm (input.hidden-input)
  3x -0:49.7.0 core:move-left (input.hidden-input)
  3x -0:44.6.0 core:copy (input.hidden-input)
  2x -0:41.5.0 editor:select-to-end-of-word (input.hidden-input)
  2x -0:40.4.0 core:copy (input.hidden-input)
     -0:39.1.0 core:paste (input.hidden-input)
     -0:22.7.0 core:close (input.hidden-input)
  5x -0:18.8.0 core:select-down (input.hidden-input)
     -0:17.7.0 core:backspace (input.hidden-input)
     -0:17.1.0 core:move-left (input.hidden-input)
     -0:16.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 13.5.1 
busy-signal 2.0.1 
emmet 2.4.3 
firestore-rules-grammar 0.4.0 
hyperclick 0.0.0 
ide-json 0.2.1 
ide-typescript 0.9.1 
intentions 1.1.5 
language-hugo 0.5.1 
language-markdown 0.37.0 
linter 2.3.1 
linter-ui-default 1.8.1 
platformio-ide-terminal 2.10.0 
todo-show 2.3.2 
zentabs 0.8.9 
```

**Comment by lierdakil** [comment]
Judging from the error message, tsserver died due to a segmentation error. There might be many reasons for why that happened, from faulty hardware to cosmic rays to buggy code in Node.js.

If this is a one-off thing, it's benign enough to ignore.

If things like this happen often, the most likely reason would be faulty hardware or corrupted Node.js installation, but it is possible to debug this further if you're so inclined, by setting `window.atom_typescript_debug = true` in the Atom dev console and watching what exact sequence of commands leads to a crash. If it seems random, again, the most probable cause would be faulty hardware or corrupted Node installation, otherwise might be worth constructing a testcase and reporting it upstream.

**Comment by jaqmol** [comment]
It's not random, it happens quite often since a crash I had after installing a certain plugin that froze my machine entirely. I already tried to re-install node from nvm without any noticeable betterment. I guess I have to wipe the complete initial node installation.

**Comment by lierdakil** [comment]
> a certain plugin that froze my machine entirely

I would suspect file corruption in that case.

> complete initial node installation

Bear in mind, depending on the details of your setup, which I can't know, Atom may be using its own Node installation. Atom-TypeScript runs tsserver via Atom's Node. So you might also want to try reinstalling Atom.
