### ISSUE TITLE
Multi cursor on click broken in latest update (Core Editor Settings)

### ISSUE THREAD

**Issue by marchand-software** [TypeStrong/atom-typescript#1549]
Only thing I can think that changed was an update from this package. I've tried all the other related settings like those in atom-ide-ui.

I updated to the latest release and my "multi cursor on click" (ctrl-click) is no longer working.

**Comment by lierdakil** [comment]
Most likely you're misattributing the issue, since there were no changes in the last several updates related to that. But it's easy enough to confirm. Uninstall/disable the package, restart Atom, and try again. If it works with atom-typescript disabled/uninstalled, we can investigate further. If not, atom-typescript isn't related to the issue.

Or perhaps try using ctrl+shift+click.

**Comment by marchand-software** [comment]
Makes sense, doing so didn't change my issue. Must not be related to this package.
