### ISSUE TITLE
Error: terminated on signal: SIGABRT

### ISSUE THREAD

**Issue by ganinaleksei** [TypeStrong/atom-typescript#1584]
[Enter steps to reproduce:]

1. open atom
2. await

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Debian GNU/Linux
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.6.0

### Stack Trace

Atom-Typescript error: terminated on signal: SIGABRT

```
At Error: terminated on signal: SIGABRT

Error: terminated on signal: SIGABRT
    at /packages/atom-typescript/dist/client/client.js:160:19)
    at Object.onceWrapper (events.js:282:20)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
  2x -9:10.3.0 core:copy (input.hidden-input)
     -6:18.8.0 find-and-replace:show (input.hidden-input)
     -6:18.4.0 core:paste (input.hidden-input)
  3x -6:18 core:confirm (input.hidden-input)
     -2:22.1.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-over-and-back 0.4.0 
atom-typescript 13.6.0 
linter 2.3.1 
prettier-atom 0.60.0 
status-bar-blame 2.0.3 
TabNine 2.9.0 
```

**Comment by lierdakil** [comment]
SIGABRT is usually thrown due to some internal constraint being horribly broken (e.g. stack/heap overflow, etc). This suggests something goes wrong in the Node runtime that runs tsserver. What goes wrong exactly I can't tell you. However, I see that your Atom installation is rather outdated, perhaps updating to the latest would fix the issue.
