### ISSUE TITLE
Intentions are not highlighted in TypeScript files

### ISSUE THREAD

**Issue by aminya** [TypeStrong/atom-typescript#1586]
If I change the extension of a file to JavaScript and hold CTRL, the intentions are highlighted, but in TypeScript, nothing is returned by atom-typescript.

**Comment by lierdakil** [comment]
Well, we do provide intentions:highlight service, and it ostensibly should work for regardless of file format. However, tsserver doesn't really have a way to request all available code fixes efficiently, only get code fixes for the current cursor position, and iterating over every possible document position would just be incredibly slow. So what we actually do is iterate over reported errors (which are more likely to have code fixes attached). No errors mean we can't display any code fixes, really.

Disclaimer: it's been a while since I really sifted through tsserver's API, perhaps in newer versions there _are_ ways to get all available code fixes, I am just not aware of it.

**Comment by aminya** [comment]
But the only difference here is the file extension. Why one of them is fast and the other isn't? Is it because of type checking?

**Comment by lierdakil** [comment]
Eh... my guess is you're probably getting js highlights from another package.
