### ISSUE TITLE
Quick-fix not working anymore

### ISSUE THREAD

**Issue by Nilos** [TypeStrong/atom-typescript#1591]
I use the quick-fix feature a lot (Ctrl+Enter) on my mac, but recently it stopped working.

I've tried installing an old version and even re-installing atom from scratch, nothing helped.

Any idea on how I could debug the issue? Is this only a problem for me?

**Comment by lierdakil** [comment]
Sorry for the late reply. As far as I can tell, you're referring to code actions via `intentions`? For one, check that nothing steals that `ctrl+enter` keypress (use `key-binding-resolver:toggle` from the command palette). If you're using some other ide-ui let me know which one, since there are a few.
