### ISSUE TITLE
getOrCreateProjectFile is broken (for d.ts files?)

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#170]
Comment says “creation is done in memory (for .d.ts)” but it tries to load a tsconfig.json from the filesystem and crashes with ENOENT.

It also doesn’t seem to be looking up the file hierarchy to find a tsconfig.json in a parent directory.

**Comment by basarat** [comment]
> It also doesn’t seem to be looking up the file hierarchy to find a tsconfig.json in a parent directory.

It will not find the tsconfig.json if this `.d.ts` file is the first one you open https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L248-L261. Otherwise it would hit it in the cache. https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/projectService.ts#L84 

This code https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L248-L261 definitely needs to be moved into `projectService.ts`. Sorry for this bad code. 

> Comment says “creation is done in memory (for .d.ts)” but it tries to load a tsconfig.json from the filesystem and crashes with ENOENT

I'm not sure how its happening

**Comment by basarat** [comment]
> definitely needs to be moved into projectService.ts

I've cleaned up the code so all the logic is in `projectService.ts` `getOrCreateProjectFile`: 

* stuff in lib.d.ts folder is each its own project : https://github.com/TypeStrong/atom-typescript/blob/d24c28f401f4d1c1a0df12f2fde7323f32ecb35d/lib/main/lang/projectService.ts#L112-L115 
* Only if the project file is not found && the file is a `.d.ts` file. Then it is its own project : https://github.com/TypeStrong/atom-typescript/blob/d24c28f401f4d1c1a0df12f2fde7323f32ecb35d/lib/main/lang/projectService.ts#L123-L126 
* Everything else we try to create a project on disk : https://github.com/TypeStrong/atom-typescript/blob/d24c28f401f4d1c1a0df12f2fde7323f32ecb35d/lib/main/lang/projectService.ts#L129-L131 

Please reopen if you have any concerns with this :heart:
