### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#198]
Ideas:
- Start worker only on first `.ts` file.

**Comment by kolis** [comment]
+1
The TS package is the largest contributor to my package loading time, as reported by the TimeCop command.


I have a total of 105 packages, loaded in 675ms, of which atom-typescript consumes 584ms

**Comment by PierreAnctil** [comment]
+1
Currently adds 4510ms to my startup time

**Comment by manucorporat** [comment]
+1

**Comment by prijindal** [comment]
It adds 87601ms to my startup time
![atomtypescript](https://cloud.githubusercontent.com/assets/10034872/13495461/bea8d60e-e0ff-11e5-99d4-213953a150b1.PNG)

Maybe you can improve the performance by inititalizing when a .ts file is opened or a project with tsconfig is opened

**Comment by swreeser** [comment]
![image](https://cloud.githubusercontent.com/assets/3954343/17538274/cd4d7b16-5e58-11e6-9242-20549d776ffe.png)
@prijindal that's absurd, I'm getting one to ten seconds
![image](https://cloud.githubusercontent.com/assets/3954343/17538325/271cfffe-5e59-11e6-9952-00596269193a.png)
Any idea what's causing this delay?

**Comment by ruppalsingh** [comment]
Adds 4191ms to my startup. Wish there'd be a fix already. Atom isn't the fastest itself.

**Comment by wyqydsyq** [comment]
Bump for attention

Using this plugin on moderately sized TS projects can easily add 20s+ to startup time from this package alone. Not sure how such a mature and widely used package is so unoptimized, surely there's people with bigger projects than me who would have 40s+ startups due to this?

![image](https://cloud.githubusercontent.com/assets/621277/23980446/37dabf5e-0a4b-11e7-8905-44a1be6e3851.png)

**Comment by lierdakil** [comment]
Closing this for housekeeping purposes. FWIW, this should've been fixed some time between v10 and v12. Feel free to open new issues if still experiencing this.
