### ISSUE TITLE
Restore functionality for `--out`

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#244]
Its okay to show that error but don't have it block functionality

refs https://github.com/TypeStrong/atom-typescript/issues/206

User should be able to get intellisence + error checks

**Comment by basarat** [comment]
This needs a bigger rewrite in the form of `warning` vs. `error` and I'm not motivated enough by this feature. Opening it up for a hero.

**Comment by nycdotnet** [comment]
Bas - I'm curious:  In theory, with a TypeScript AST, would it be possible to programmatically figure out an appropriate concatenation order?  I know it might not be perfect due to side-effects, but I suspect that it would be possible to at least avoid things like use-before-declare.  Now that I'm thinking about it - I think there was a GitHub issue in the TS repo about that particular thing.

**Comment by erikvullings** [comment]
@nycdotnet I second that. 
Also, instead of writing the files in tsconfig.json in alphabetical order, you could instead write them in the AST concatenation order. In that case, even if someone doesn't use the --out compiler option, a gulp/grunt script could use this file order to create a single output file.

**Comment by basarat** [comment]
> In theory, with a TypeScript AST, would it be possible to programmatically figure out an appropriate concatenation order 

Not in the absence of something like *main* (like C# / JAVA / C)

**Comment by erikvullings** [comment]
Why not specify the main class explicitly in tsconfig?

I've been using the gulp-order plugin recently. What it does is it takes a stream of input files, like the ones tsconfig generates based on the mini match, and for a subset of them, it specifies the order explicitly. So I only need to specify my base classes, and then everything can be concatenated just fine. 

Couldn't you also use such an approach for generating out files?

**Comment by basarat** [comment]
> Couldn't you also use such an approach for generating out files?

Supporting stuff like NPM modules is just easier with external modules. Note: NPM all things.

**Comment by martinmcwhorter** [comment]
I think @erikvullings may be onto something. We should be able to explicitly define a list, or a main.ts, or a references.ts, as a starting point for --out compilation. @basarat is right, that all new projects should use modules -- but it would be nice to easily use atom-typescript on older projects that use /// <references /> with -out.

**Comment by basarat** [comment]
The TypeScript compiler uses `out`. This means I can't look at the compiler source using atom typescript. Fixing this ASAP :rose:

**Comment by basarat** [comment]
`3.0.5`
