### ISSUE TITLE
Add a member to a class

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#257]
Would be great if you could get "add a member to class" style of refactoring.

![image](https://cloud.githubusercontent.com/assets/874898/7111770/a90c9612-e206-11e4-87bb-6f51c78d80af.png)

Keybinding : `alt+enter`

**Comment by filimon-danopoulos** [comment]
I would like to see this also mapped as `alt-enter` like #256. 

If possible, I would like `alt-enter` to be the standard "fix this" command. I am not sure if Atom has a good API for this but if possible. This would be a killer feature.

**Comment by basarat** [comment]
> I would like alt-enter to be the standard "fix this" command

Agreed.

> I am not sure if Atom has a good API for this but if possible. This would be a killer feature

Can be done easily (using atom services). But not my goal here :heart:.

**Comment by basarat** [comment]
And when in doubt, just ask : https://github.com/Microsoft/TypeScript/issues/2788

**Comment by filimon-danopoulos** [comment]
Sweet, I will look in to this on Friday. I'm excited!

**Comment by basarat** [comment]
@filimon-danopoulos I'm still working on this. Just documenting my process for transparency :rose:

**Comment by basarat** [comment]
After my next push: 
![fixmyts](https://cloud.githubusercontent.com/assets/874898/7177576/28465100-e46b-11e4-916e-187157403109.gif)

Next up will be type inference, followed by documentation and then this issue can be closed.

**Comment by filimon-danopoulos** [comment]
I think this would look way better as part of the original message. Instead of using the "pop-up" for lack of better term. 

So instead of 

    Property X missing on Y

we would have 

    Property X missing on Y. 
    Quick fix (alt-enter): Add member to class.

What do you think about that?

**Comment by basarat** [comment]
> Then alt-enter would immediately fix it

Also intend to (later) add stuff like "remove unused imports" which will be there in *all* `alt-enter`.

**Comment by filimon-danopoulos** [comment]
I think that might be a design flaw. When I am (and presumably other developers) typing code I don't want distractions or having to take unnecessary decisions.

In this case I want to be able to tell the editor to fix a particular error. I have already decided what I want to do and as long as there is no confusion about how to do it I would expect the editor to do it. In this case just add the member, if there are multiple choices I can be show some sort of prompt.

If I am given choices at this stage it will be disruptive. Since I am probably not interested in general refactoring functionality I should not be shown that information.

Additionally it feels like that type of command (remove imports) belongs under `ctrl-shift-p` in the atom workflow not under a general "fix-it" type command.

I might have misunderstood what you intended with quick-fix but this is not what I expected.

**Comment by basarat** [comment]
Glory: 
![addclassmember](https://raw.githubusercontent.com/TypeStrong/atom-typescript-examples/master/screens/addClassMember.gif)

> I don't want distractions or having to take unnecessary decisions

You don't have to. Press `alt+enter` followed by `enter` and it will just work :rose: (if we have done our sorting right)

**Comment by erikvullings** [comment]
That's looking just great! Almost like ReSharper.

BTW is there any particular reason that you create the first 'something' member as public. I would probably have made it private.

**Comment by basarat** [comment]
> is there any particular reason that you create the first 'something' member as public. I would probably have made it private

The target is ES6 `js` to `ts` code refactoring. The ES6 code `this.something` is assumed public.

**Comment by filimon-danopoulos** [comment]
@basarat That screencap looks quite good, I like it much better than the first draft. I wonder how you would integrate other refactor functionality into this menu without making it unclear?

**Comment by basarat** [comment]
> other refactor functionality into this menu without making it unclear?

Refactoring can (in future) come with an optional html display string :) with embedded icons 🌹
