### ISSUE TITLE
tsconfig files list makes source control checkin difficult

### ISSUE THREAD

**Issue by park9140** [TypeStrong/atom-typescript#266]
filesGlob is a nice way to reduce churn on file lists in the tsconfig.  However, after adding it atom updates the tsconfig ever time you add a file to complete the files list.  

I would love to use tsconfig as part of our build process, but having a change to this file every time a new file is added to the project creates massive churn and constant merge conflicts.  

Can we make it so the file list cache is posted into a cache file instead that can be separately git ignored?

**Comment by basarat** [comment]
> file list cache is posted into a cache file

Its not a cache. We evaluate `filesGlob` irrespective of what `files` says. The reason why `files` exist is because the official spec only supports `files` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#tsconfigjson So we actively keep `files` in match with `filesGlob` so that you can use the project with stuff like sublime text. Sadly `files` *needs* to be in `tsconfig.json` even though *we actually don't care to use it in presence of `filesGlob`*. :rose:
