### ISSUE TITLE
Expose Project API as a service

### ISSUE THREAD

**Issue by tswebcomponents** [TypeStrong/atom-typescript#291]
I'm working on a demo/POC to provide autocompletion for typed webcomponents (Polymer/Typescript). To realize this I transform polymer elements (html) to a typescript class so I will have a view class that can be used to typecheck and for autocompletion etc. TypeScript class will map to html element tags and attributes/values.

The autocompletion is implemented as a provider for the autocomplete-plus package and will consume the Symbols from the atom-typescript Project API. The navigateTo API's are not complete enough to provide the information as I need the parent-child relationships between symbols (class-properties-methods) to provide autocompletion for element attributes etc.

What would be the proper way to implement this? (I now added a method getNamedDeclarations(...) to the project API) and will this be provided in the future?

Another approach would be to use the language service directly, but this isn't exposed from the atom-typescript package also is it? (or is there another way to achieve this besided the Atom provider/consumer pattern, like https://discuss.atom.io/t/depending-on-other-packages/2360.

**Comment by basarat** [comment]
Some context: 

Nothing is exposed from the atom-typescript package. Although it can be. I am familiar with the services API.

We run the languageService in a background process : https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#architecture so that the UI doesn't become sluggish. 

-------------

> will consume the Symbols from the atom-typescript Project API.

Exposible. 

> I now added a method getNamedDeclarations(...) to the project API) and will this be provided in the future

I am pretty much in the same boat as you. Try and test till it works :+1:. If in doubt ask Microsoft/TypeScript :rose:

**Comment by tswebcomponents** [comment]
And are there any plans to expose the languageService to other packages? What I need are the named declarations from the program, so I need the languageService or at least the sourceFiles of the program. Is there a way to get these without extending the ProjectService?

Thanks.

**Comment by basarat** [comment]
> And are there any plans to expose the languageService to other packages?

That is doable. I will give you our API endpoint "GetOrCreateProject"

**Comment by tswebcomponents** [comment]
Thanks for the info. Still not clear to me how I will get to the "program" that provides the getNamedDeclarations?

**Comment by tswebcomponents** [comment]
@basarat: any updates on this issue or maybe a hint how to implement this at this moment? As mentioned I don't completely understand by your previous comment and how to get to the language service from the parent module from another Atom package. I think the projectService and parent service would need a getProject():Project method or something like that to realize this (I now have this working with this solution) or do I completely misunderstand the topic?

Thanks in advance.

**Comment by basarat** [comment]
> any updates on this issue

sorry none yet. 

> maybe a hint how to implement this at this moment

Expose this `parent` variable : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atomts.ts#L47 as a provided service. I will work on this once done with other quite big tooling gaps in TypeScript land

**Comment by tswebcomponents** [comment]
@basarat : I understand what to do, but the parent doesn't expose a method or property with what I can access the project and from there the languageService can I? I solved my problem now by requiring the projectCache and invoke the getOrCreateProject that returns the project I need.

Maybe this method should also be exposed in the projectService and parent or am I wrong?

Thanks!

**Comment by basarat** [comment]
Extremely sorry for the late reply. 

> but the parent doesn't expose a method or property with what I can access the project and from there the languageService can I

Yes it doesn't expose the LS. The parent functions synchronously in the UI process talking to projectService via JSON (see design https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#architecture).

> I solved my problem now by requiring the projectCache and invoke the getOrCreateProject that returns the project I need.

That is okay ... but be warned that we now effectively have *two* project caches .... one running in the UI process (because that is where you are calling it from) and one running in the background (that we interact with using `parent`). 

We keep the background one in sync with changes in the editor. The one you've created in the UI process is effectively a file system snapshot and changes in an unsaved editor instance are not pushed to it.
