### ISSUE TITLE
Using in vanilla JS / JavaScript projects

### ISSUE THREAD

**Issue by Cortys** [TypeStrong/atom-typescript#315]
Is it possible to use this package for vanilla js?

Even without the type annotations, TypeScripts autocomplete suggestions are a lot better than those of most other Atom packages I tried.

**Comment by basarat** [comment]
> Even without the type annotations,

sadly not at the moment. The TypeScript compiler is really stingy about file extensions. And we've followed this convention *deep* within our code. 

Leaving open as a wishlist :rose:

**Comment by scottwio** [comment]
For me this is more about being able to use some of typescripts abilities without having to change the workflow of everyone on the team. For a lot of people even changing the file extension is to much as they are js purists aka don't like the idea of typescript. This way you can work along side another js dev without effecting them at all. 

I wonder how Visual Studio Code has implemented the feature as they are just using the standard ts compiler.

**Comment by dbroadhurst** [comment]
+1 It would be great use TS features in .js files

**Comment by nycdotnet** [comment]
It seems the TypeScript team agrees.  Take a look at the items tagged salsa on their issues list.  This may be coming in a future language service version, in which case I assume we'd add support for it.

**Comment by cebor** [comment]
:+1:

**Comment by andrew-w-ross** [comment]
+1

**Comment by PanayotCankov** [comment]
:+1:

**Comment by everwonder** [comment]
:+1:

**Comment by aminroosta** [comment]
:+

**Comment by IdanAdar** [comment]
+1

**Comment by basarat** [comment]
Foreword: I will most likely not get to it anytime soon.

TypeScript has officially unleashed the `allowJS` option : http://blogs.msdn.com/b/typescript/archive/2016/01/28/announcing-typescript-1-8-beta.aspx 

So about time we support it. Not marking as up for grabs as reviewing this is going to be just as much work as adding and then supporting it. The following is a list of tasks that needs to happen

* [ ] allowJS in tsconfig compiler options
* [ ] change the default glob based on that 
* [ ] change the default project creation result to at least output the key so the user can change it easily 
* [ ] change the activation mechanism to activate on `.js` files as well

My BIG concerns are:

* not fighting with other packages that also work on `.js` files e.g. tern
* slowing down atom for JS files as atom-typescript is a bit bulky (mostly because that hasn't been my focus, TS projects tend to not be as messy as JS files). 

Let me sit on it :-/ I am open for other ideas.

**Comment by MarlonFan** [comment]
+1

**Comment by Tabjy** [comment]
+1

**Comment by gfrancischini** [comment]
+1

**Comment by ericelliott** [comment]
> not fighting with other packages that also work on .js files e.g. tern

Tern's hints are OK, but the UI is awkward compared to this plugin. There's a lot of overlap. My plan as a user was to remove tern and replace with atom-typescript.

I think we could simply document that users should disable tern if they want to use atom-typescript on JavaScript files.

**Comment by basarat** [comment]
It is now up for grabs. Also this project needs a new hero : https://github.com/TypeStrong/atom-typescript/issues/980 :rose:
