### ISSUE TITLE
Shortcut for closing find reference view

### ISSUE THREAD

**Issue by tinganho** [TypeStrong/atom-typescript#319]
It would be awesome if there where a shortcut for closing find reference view like `esc`.

**Comment by basarat** [comment]
Currently its `ctrl+;` to bring up the context view and then press enter.

That said I've just pushed stuff so that the reference view doesn't *open* by default. You can click it to toggle it. **And** references show up as a dropdown :rose: Much better IMHO.

![image](https://cloud.githubusercontent.com/assets/874898/7424553/022e5f4a-efe6-11e4-9df3-ec439575c3ef.png)

I'll be reviewing a better UI framework and how to embed them in atom shortly.
