### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#329]
I'm currently working with the Aurelia framework which uses Systemjs as the module loader. In the config.js for Systemjs, I'm able to configure aliases for paths, which of course do not resolve in Atom. I would like the ability to either reference paths again or create an alias for the path so that it resolves properly.

Is there a reason the `/// reference` does not work anymore? Sometimes I just need to import the typing from another file (that's not a `d.ts`), but don't actually need to import the class directly.

Example
```javascript
class SpecialClass {
  constructor() {
    // do some stuff
  }
}
```
I would just reference here
```javascript
class MyOtherClass {
  constructor(store: SpecialClass) {
    // Do stuff
  }
}
```
If I use `import {SpecialClass} from 'specialclassfile'` it will insert `var SpecialClass = require('specialclassfile')` which is the expected behavior, however I only want to reference the file for type information.

Thanks in advance.

**Comment by Aedaeum** [comment]
It seems like this is a bigger issue then I thought it was. @cmichaelgraham and I were trying to figure a way around my issue and decided to go the route of enabling `"declarations": true` in the `tsconfig` file.

What I ended up discovering is my declaration file added the following lines, in order to support the types I was using.
```javascript
import { Page } from 'helpers/page';
import { Message } from '../elements/message/message-view';

interface CommanderData {
    sock: Socket;
    chatView: Chat;
}
```

I then proceeded to use my `CommanderData` interface, however it kept telling me the name was not found. I decided to manually go through the auto-generated definition code piece by piece, until I discovered that commenting out the import statements allowed the `CommanderData` interface to be used globally.

Conclusion... Import statements break definition discovery, at least in this specific case. If you need more information, let me know.

**Comment by basarat** [comment]
The following is my line by line analysis of your message. The final outcome : by design, needs work in the compiler :)

> Is there a reason the /// reference does not work anymore

They should still work. 

> however I only want to reference the file for type information.

FWIW If the file is an *external module* i.e. has a root level `import / export` then it cannot be `///referenced` 

> Here was the auto-generated declarations file

Yup, you can see you have root level `import` / `export` (import { Message } from 'elements/message/message-view';
export `). Such files cannot be `///ref`ed. This is in the design of the compiler. 

> Import statements break definition discovery, at least in this specific case. If you need more information, let me know.

Sorry, by design. The plan forward is (https://github.com/Microsoft/TypeScript/issues/2338) you should be able to `import/require` such `.d.ts` files and these `.d.ts` files should live *right next to the actual `.js` files*. That way the compiler reads `.d.ts` and the runtime reads `.js`. Unfortunately I haven't had the time to help out implementing 2338.

**Comment by Aedaeum** [comment]
Thanks, I'll keep watch of this.
