### ISSUE TITLE
Error notification off screen

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#347]
This is getting particularly annoying in my case, since I have an object which is telling me that its type is not the same, when clearly it is, however.... Since the error message posts off the screen, I have no way of knowing what type it thinks is an invalid comparison.
![image](https://cloud.githubusercontent.com/assets/2054218/7663084/b47faf12-fb19-11e4-8c1e-c08b05993bb2.png)

I did notice that I could open the console pane below for the entire error, but it would be nice if it could properly line-break the message.

**Comment by basarat** [comment]
really belongs in `atomlinter/linter`. Created an issue for tracking : https://github.com/AtomLinter/Linter/issues/533

**Comment by helarqjsc** [comment]
This issue should be closed, because the problem was fixed in AtomLinter. It does wrap properly now:
![Screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_45718/DjfDC6SOK1FSsZ3R86vBajtnDzui4M/linter.ts%2B-%2BC__xampp_htdocs_atom-typescript%2B-%2BAtom%2B2015-07-03%2B12.20.01.png?Expires=1435994409&Signature=k6pDwc5NUXzXTQ3OvgkDWcafBK2d42d4VAUptecyTLO2iGsBiXW9GELU3ibu8L5wxRKYBDjgvyprFLH24w2g9vnuyQtg1Tr-fFo6VfqZeCbbE5D7kXuk7xDNuMzh2HKev-NbwApMDUeiaORkcAOmTit56vW7bm9OtSJMtXuDUODaomiiDb48anlxIgruYRfiW-TIvPmzoyiag1qOywK5ARiDWyI7NBocg0TAAiiOogDB91pAYqt5Kuaj8moavboUJ0I9l8vhwADfuX7BsEcSA8vCYtuPTq~2e3L5B92Qp8EPlGaibye3erpfKIuLCNlq7Jk4ybxElpxGudWr2h12tQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by Cu3PO42** [comment]
Thanks @helaeqjsc!
