### ISSUE TITLE
I'm getting errors while typing

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#348]
Since the update to `v4.3.0` I've been getting errors as I type, which prevents any kind of code-completion (not in all cases) from popping up. This also effects lines that when saved, are immediately shown to be valid...

This is valid code, and yet the editor is marking errors for no apparent reason. This was all working just fine before updating to the latest version.
![image](https://cloud.githubusercontent.com/assets/2054218/7663333/a285c0cc-fb1d-11e4-8645-55a1b070e938.png)

As soon as I `CTRL+S` to save, it immediately validates and the error markers go away.

**Comment by basarat** [comment]
This is because of atom's poor notification of exact changes in the presence of new lines : https://github.com/TypeStrong/atom-typescript/commit/c82312d0051fe5cf9324335df0b76840592f2701#diff-ed09a6b54d1678ad915acb85684ad75f 

I've reverted and pushed a patch. Will investigate a more permanent fix :rose:

**Comment by Aedaeum** [comment]
Excellent :smile:
