### ISSUE TITLE
Possible autocomplete+ provider priority issue

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#353]
As far as this issue: https://github.com/atom/autocomplete-plus/issues/465 is concerned, I talked to one of the devs who mentioned that setting the priority >2:
![image](https://cloud.githubusercontent.com/assets/2054218/7672064/d5a7955c-fc99-11e4-9fb5-b8bd1269d913.png)
Should fix the issue.

I also want to say thanks for all your hard work @basarat it's much appreciated. You're probably getting tired of all the issues I keep creating :stuck_out_tongue_winking_eye:

**Comment by basarat** [comment]
The snippets don't show reliably at the moment. That issue was reported : https://github.com/atom/autocomplete-snippets/issues/46

They thought it was because of priority so they increased it to 2 https://github.com/atom/autocomplete-snippets/issues/46#issuecomment-100318173 

I'd rather not get into a priority war at the moment :) I'll see what other providers are doing :+1:

**Comment by basarat** [comment]
> I'll see what other providers are doing

They seem to prefer snippets on top i.e. none of these provide a priority : https://github.com/atom/autocomplete-atom-api/blob/master/lib/provider.coffee && https://github.com/atom/autocomplete-html/blob/master/lib/provider.coffee && https://github.com/atom/autocomplete-css/blob/master/lib/provider.coffee

**Comment by basarat** [comment]
I'll make it 3. Since omnisharp did the same https://github.com/OmniSharp/omnisharp-atom/pull/305/files

**Comment by Aedaeum** [comment]
I can't imagine why anyone would prefer snippets above actual object completions, when in that context they're out of scope... Anyway, I'm glad this is solved :smile:
