### ISSUE TITLE
Refactor failing inside string template

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#358]
Before (Take note of `begin`):
![image](https://cloud.githubusercontent.com/assets/2054218/7730735/ce582ecc-fed0-11e4-8b54-4e99499a84df.png)

After:
![image](https://cloud.githubusercontent.com/assets/2054218/7730746/e93b5764-fed0-11e4-848d-ff4f8e1a9454.png)

**Comment by basarat** [comment]
I suspect this might be related to https://github.com/TypeStrong/atom-typescript/issues/359 since its an off by one bug (`\n` instead of `\r\n` inside atom's event system). 

Seems to be fixed now: 

![meh](https://cloud.githubusercontent.com/assets/874898/7742339/665cf3f0-ffd1-11e4-97cf-9f273f55f26a.gif)
