### ISSUE TITLE
Function params/args identification

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#360]
You'll be happy to know this is just a feature request :smile: 

It would be really helpful to have this:
![image](https://cloud.githubusercontent.com/assets/2054218/7755273/bc62c39e-ffa7-11e4-9f45-cd03d2ba8511.png)

Currently, we either get an error because the params are not provided, or nothing at all if no params are required.

_screen shot taken from VS Code_

**Comment by basarat** [comment]
Go inside a `console.log()` and press ctrl + space:

![image](https://cloud.githubusercontent.com/assets/874898/7761282/404ff78e-0067-11e5-9f1c-18da937fa348.png)

Doesn't show up by default because of https://github.com/atom/autocomplete-plus/issues/329

Being tracked locally here : https://github.com/TypeStrong/atom-typescript/issues/23 (so marking this as duplicate, unless I've misunderstood the issue?

**Comment by Aedaeum** [comment]
Ah, okay, yes that was what I was looking for. I tried to search for it, but I didn't find that issue.
