### ISSUE TITLE
cpu freaks out if I write long comments in .ts files 

### ISSUE THREAD

**Issue by alexwall** [TypeStrong/atom-typescript#396]
When I start to write a comment after // (comment) the cpu usage is very high

**Comment by basarat** [comment]
Is it at *the start of a file* that has a lot of lines *after the point of insertion of `//`*?

**Comment by alexwall** [comment]
In my case it is in the middle of file with 250 lines. But you can just create a .ts empty file and then start to write a comment (no matter if // or /* */).

**Comment by basarat** [comment]
Can you test on a .js file? (Basically I am curious if it is in atom's grammar or typescript's language service)

**Comment by alexwall** [comment]
Writing in a .js file results in less cpu usage and feels smoother. Writing in a .ts seems to have small delay and larger cpu usage.

**Comment by basarat** [comment]
Cool. I'll investigate more then :rose: :+1:

**Comment by alexwall** [comment]
:)

**Comment by Cu3PO42** [comment]
@alexwall can you still reproduce that behavior after updating to the latest version (it included a massive grammar rewrite) because I can't seem to notice a difference.

**Comment by alexwall** [comment]
I have an Mac Book Pro Late 2008 (2,4 GHz Intel Core 2 Duo) and when I type fast I get this cpu usage in Activity Monitor:

1. 65% AtomHelper (first Instance)
2. 30% WindowServer 
3. 15% AtomHelper (second instance)

*maximum is 200% because of Core 2 Duo

So after updating Typescript Plugin to 5.0.10 (and now on 5.0.11) from 4.x.x (I don't remember old version) it feels more snappy and I don't feel glitches/delays while typing.

I would say, the cpu usage is similar the same like before BUT it feels better to type, which was the important part for me.
Now it feels like writing in a javascript file and *not only* in the comments area. This is great!

Thanks!!!
 
PS: Maybe it is possible to disable code "intellisense" additionally when writing comments

**Comment by Cu3PO42** [comment]
You'd have to expect the CPU usage to be higher than when writing JS, because the TS grammar includes a lot of very complex rules with huge RegExes. However I'm glad you get a fluid experience, as do I.

Concerning autocomplete suggestions in comments, I don't get that. Can you describe exactly how to reproduce that, provide screenshots, or preferably a small gif demonstrating that behavior, please?

**Comment by alexwall** [comment]
What I mean is, do we need grammar checks when writing comments? And if not, is it possible to disable them to avoid unnecessary cpu work?

**Comment by Cu3PO42** [comment]
I didn't mean specifically grammars when I said the grammar was a lot more complex. And yes, there needs to be some grammar checking going on while writing comments. However it is reduced. When you're writing a multi line comment, once you leave the first line we only look for the end token. While in the first line all language checks are still done due to the way TextMate grammars work. However CPU usage shouldn't be any higher than while writing normal code.

**Comment by alexwall** [comment]
Oh it was a misunderstanding. I never said that writing comments has a higher cpu usage than writing code. I just didn't understand why writing comments has also a high cpu usage. 
And the actual problem was the delays and glitches while writing, because I write  comments faster than code and this was annoying ;)

I thought that the high cpu usage was the cause for this problem and created this issue.

But now writing code and comments feels good!

Thanks!
