### ISSUE TITLE
Instead of "no emit requested" would be great to show the actual JS vs. TS comparison

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#416]
refs https://github.com/TypeStrong/atom-typescript/pull/415

**Comment by nycdotnet** [comment]
I do miss the ability to see the emitted JS in an easy manner.  While I don't care for the web essentials-style split screen, it is useful from time to time.  I wonder if it would be possible to enable some sort of keyboard shortcut to "pop" the emitted JS out in a floating window.  Perhaps a bit like a code lens preview.  This would be tricky because it would need to work with source maps.

**Comment by nycdotnet** [comment]
@basarat Did you make a recent change to disable the "this file changed - do you want to reload?" prompt when looking at the emitted JS and TS in the same view as a split-screen?  Or was this a recent change in Atom?  Now it appears that the viewed JS file immediately refreshes when the TS compiles-on-save as long as you haven't made any changes in the JS file directly.

I notice we also have the same problem as Web Essentials used to where the emitted JS scrolls to the top when the file is refreshed.  If you didn't make this change then perhaps this is an Atom bug.

**Comment by basarat** [comment]
> I do miss the ability to see the emitted JS in an easy manner

Already there : https://github.com/TypeStrong/atom-typescript#output-toggle

> where the emitted JS scrolls to the top when the file is refreshed. If you didn't make this change then perhaps this is an Atom bug.

Verified that this happens now. Its a atom bug nothing to do with us :rose:

**Comment by nycdotnet** [comment]
> Already there : https://github.com/TypeStrong/atom-typescript#output-toggle

I do need to keep more up to date on the patch notes.

**Comment by basarat** [comment]
fixed with https://github.com/TypeStrong/atom-typescript/pull/422 thanks to @helarqjsc :rose:
