### ISSUE TITLE
Render markdown as HTML in documentation tips

### ISSUE THREAD

**Issue by Ciantic** [TypeStrong/atom-typescript#420]
This is feature request, and maybe a bit contentious since such decisions usually is taken in language spec level.

But I would love to see tooltip rendered as HTML when I type markdown in my comments.

E.g.
```typescript
/**
 * This function is helper for `CreateObject.foo()`
 **/
function bar(d) {

}
```

Should render in Atom Tooltip as: This function is helper for `CreateObject.foo()`

I took the idea shamelessly from Swift and Xcode.

**Add** Maybe it could be configurable from tsconfig.json? `"docs" : "markdown"`

**Comment by basarat** [comment]
I would like this as well. 

> Maybe it could be configurable from tsconfig.json? "docs" : "markdown"

Perhaps later. I *think* we should be able just *switch it on* without any aweful issues

**Comment by basarat** [comment]
Even though I like it I don't want to deviate on the UI experience on this one, so closing as I don't want someone else to put any effort in this.

**Comment by basarat** [comment]
I have since reconsidered this stance. Especially since typedoc already renders these as markdown :rose:

I've done the same in [alm.tools](http://alm.tools/) in tooltips : 

![image](https://cloud.githubusercontent.com/assets/874898/15417888/e24d87cc-1e9d-11e6-8560-bbe6f28567d7.png)


As well as in the documentation view : https://basarat.gitbooks.io/alm/content/features/documentation-view.html

![live](https://cloud.githubusercontent.com/assets/874898/15417894/f3229c18-1e9d-11e6-879c-dbb1b6e276de.gif)
