### ISSUE TITLE
Failed to load Typescript Package - Cannot read property 'React' of undefined

### ISSUE THREAD

**Issue by LivesleyWA** [TypeStrong/atom-typescript#489]
1. Install version 5.2
2. Start Atom
3. Error message shown on startup

I have removed and reinstalled - no change

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v5.2.0

### Stack Trace

Failed to load the atom-typescript package

```
At Cannot read property 'React' of undefined

TypeError: Cannot read property 'React' of undefined
    at Object.<anonymous> (/Users/xxx/.atom/packages/atom-typescript/dist/main/tsconfig/tsconfig.js:75:20)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/xxxx/.atom/packages/atom-typescript/dist/main/lang/projectService.js:9:16)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "solarized-light-syntax"
    ]
  },
  "atom-typescript": {
    "typescriptServices": "/Users/xxx/source/xxx/node_modules/typescript/bin/typescriptServices.js"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.2.0
docblockr, v0.7.3
language-html-swig, v2.0.1
last-cursor-position, v0.9.0
less-autocompile, v1.0.0
linter, v1.2.4
pain-split, v1.4.0
project-manager, v1.15.11
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by LivesleyWA** [comment]
Ignore this. It appears to be because I am using Typescript 1.5 beta. If I remove the reference to /Users/xxx/source/xxx/node_modules/typescript/bin/typescriptServices.js in atom-typescript configuration the problem disappears.

I'll leave this issue just in case anyone else encounters the same.

**Comment by basarat** [comment]
> I'll leave this issue just in case anyone else encounters the same.

I'll close it as its a user configuration error, and will still be searchable by words of the error :rose:

**Comment by LivesleyWA** [comment]
This isn't a user configuration error, it's an issue with Atom and Typescript 1.5 beta. The configuration was working fine until I upgraded the version of Atom Typescript. Not sure when 1.5 is to going to be released but it's worth checking before it is.

**Comment by krvikash35** [comment]
I am not sure which version of typescript is shipped with atom-typescript.
In latest typescript 2.0.0 , there is some feature that i am trying to use. one of those feature is to give typeRoots and types in tsconfig

atom-typescript-version: 10.1.6
I am providing below configuration in tsconfig.json
"compilerOptions": {
        "typeRoots": ["../node_modules/@types"],
        "types": ["core-js", "jasmine", "node" ]
    }
I am trying to use new feature of ts2.0.0 .

but when i build through atom-typescript, it throw a lot of error. like 
can't find module 'promise' 'set' etc....and i m sure its due to atom-typescript is not recognizing those new option in tsconfig.json.

I also tried providing alternate tsc complier throug project setting like below, but did not work.
"atom-typescript":
    typescriptServices: "/home/user/workspace/demo/node_modules/typescript/lib/typescriptServices.js"

But when i trying to compile from command line, then no error.
typescript installed through node is 2.0.0 but i m not sure of typescript shipped with atom-typescript

please help on this
