### ISSUE TITLE
Is there a way to have a stable version?

### ISSUE THREAD

**Issue by aleksey-bykov** [TypeStrong/atom-typescript#516]
Every  time I open atom (with typescript) I see all different sorts of problems that were not there when I closed it. It's getting old and annoying. Where is that option that prevents bleeding edge updates from being installed?

**Comment by aleksey-bykov** [comment]
![image](https://cloud.githubusercontent.com/assets/937933/9074528/73c35c4a-3ad8-11e5-82a9-9c2f2c97162a.png)


https://github.com/TypeStrong/atom-typescript/issues/211

**Comment by basarat** [comment]
> I see all different sorts of problems that were not there when I closed it. It's getting old and annoying

I definitely feel your pain. This is the reason why I moved away from (a technologically better) custom grammar to just plain old CSON (as its documented and stable)

In this case the issue you are pointing to (#211) *both instances were user errors*: 

* First (closed without reason) https://github.com/TypeStrong/atom-typescript/issues/211#issuecomment-87378526 
* And then (using custom typescriptServices) https://github.com/TypeStrong/atom-typescript/issues/211#issuecomment-113862098 

So blame can't really be put on stuff that *we* are doing. 

I'd be happy to help debug *why #211 is occurring for you* :rose: 

> Where is that option that prevents bleeding edge updates from being installed?

If you are happy with the package ... just stop updating it ;) We don't push updates to users automatically. However if new versions of Atom break the package ... then you probably want to update as we will only fix that in the latest package iterations.

**Comment by aleksey-bykov** [comment]
this is what happens:

![image](https://cloud.githubusercontent.com/assets/937933/9095339/b7ceadb6-3b84-11e5-953b-a3fd112109e3.png)

the file at `C:\Users\Bykov\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js` has:

```
    ...
    isolatedModules: false,
    jsx: ts.JsxEmit.React,             // <-- ts.JsxEmit is undefined
    experimentalDecorators: true,
    ...
```

now this file is a static part which is shipped with a atom-typescript package and assigned a version number, am I correct so far?

then you guys say: https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#which-version-of-typescript-does-atom-typescript-use

> It uses ntypescript which is just a build of Microsoft/Master. This means it's the latest and greatest of the TypeScript goodness. There is a possibility that in the future it will move to TypeScript nightlies which is something that the TypeScript team is planning.

which is clearly a work in progress that may or may not work with that static part

if so, how can this 
> just stop updating it 
be a solution?

:rose

**Comment by basarat** [comment]
> .. just stop updating it .. be a solution?

We ship with an *exact* version of `ntypescript` ... not the latest (see [package.json](https://github.com/TypeStrong/atom-typescript/blob/424ffb949d5da4bb2cbd83867d084732c59fc255/package.json#L56) for version) ... So if atom-typescript doesn't update ... neither does ntypescript. 

I guarantee you that if you reinstall atom-typescript right now `apm uninstall atom-typescript` / `apm install atom-typescript` and then don't update it *like ever*, nothing will break ... till you want newer typescript features, or newer atom-typescript features.

--------------------

I suspect in your case an *update* has gone wrong because of this issue : https://github.com/TypeStrong/atom-typescript/issues/195 which is an issue with atom really. I'm waiting on [IOJS to get worker support](https://github.com/nodejs/io.js/pull/2133) so that we don't spawn a background process that blocks file deletion on windows :rose: 

Also perhaps atom isn't respecting `package.json` semver on update (it should run npm install and get the *exact* version of ntypescript that matches the new version of atom-typescript) ? < difficult to tell without access to your file system.

**Comment by aleksey-bykov** [comment]
> I guarantee you that if you reinstall atom-typescript right now apm uninstall atom-typescript / apm install atom-typescript and then don't update it like ever, nothing will break ... till you want newer typescript features, or newer atom-typescript features.

just did:

```
C:\Mine\essentials\tools>apm uninstall atom-typescript
Uninstalling atom-typescript done

C:\Mine\essentials\tools>apm install atom-typescript
Installing atom-typescript to C:\Users\Bykov\.atom\packages done
```

didn't help

still see the same screen

![image](https://cloud.githubusercontent.com/assets/937933/9126776/db8eea94-3c7f-11e5-8053-bed25d23cde6.png)
