### ISSUE TITLE
tsx files not being recognized without the use of "files" option in tsconfig.json

### ISSUE THREAD

**Issue by priyatham-aps** [TypeStrong/atom-typescript#536]
That.

Getting the following error:
>The file "mycomponent.tsx" is not included in the TypeScript compilation context. If this is not intended, please check the "files" or "filesGlob" section of your tsconfig.json file.

We do have ```rootDir``` option enabled in ```tsconfig.json``` and ```.ts``` files are being recognized just fine.

Could you let me know if this is a bug or if I am missing something?

Thanks.

**Comment by nycdotnet** [comment]
Do you have a filesGlob element set up?  If so, what does it say?

**Comment by priyatham-aps** [comment]
It works fine when ```filesGlob``` is used as it ultimately does generate ```files``` option.

But I would expect the plugin to work even without it. ```.ts``` files seem to have no problem without that option, so why would ```.tsx``` files need it? Also, ```tsc``` does not need it to be present in ```tsconfig.json```.

**Comment by basarat** [comment]
Make sure that `files` contains the `.tsx` file. If you don't want to write `files` yourself please expand the `filesGlob` to add `./**/*.tsx` :rose: 

Our old default filesGlob in tsconfig.json files created by us didn't contain `.tsx` because tsx wasn't a thing back then. 

If you have any confusion feel free to share your tsconfig.json and we can guide you more.

**Comment by basarat** [comment]
> tsx files not being recognized without the use of "files" option

Sorry. This was a bug. Thanks for reporting. My bad, should have read it better. Fixed with `v5.4.2` :rose:

**Comment by priyatham-aps** [comment]
Great! It's working now. Thanks.
