### ISSUE TITLE
Syntax highlighting lost in definition file when using `extends` followed by `implements`

### ISSUE THREAD

**Issue by bgrieder** [TypeStrong/atom-typescript#613]
Definition File
Atom: 1.0.16
atom-typescript: 6.0.17
all themes

<img width="502" alt="screen shot 2015-09-24 at 08 42 20" src="https://cloud.githubusercontent.com/assets/797684/10066970/375526c0-6298-11e5-8564-d04fce151989.png">

    declare module "highlighting" {

        export interface I {}

        export class E0 extends Error {
            OK: string
        }
        export class E1 extends Error implements I {}
        export class E2 extends Error {
            NotOK: string
        }
    }

**Comment by basarat** [comment]
> Atom: 1.0.16

Broke with this atom release. Also https://github.com/TypeStrong/atom-typescript/issues/611#issuecomment-143085486 and https://github.com/TypeStrong/atom-typescript/issues/614

**Comment by basarat** [comment]
fixed with https://github.com/TypeStrong/atom-typescript/releases/tag/v7.1.0 :rose: 

Note the fix is that we break type grammar rule on new lines ... so the same line might still be weird but following lines will start highlighting correctly. 

<img width="472" alt="screen shot 2015-10-04 at 4 03 17 pm" src="https://cloud.githubusercontent.com/assets/874898/10266483/9d151468-6ab1-11e5-9aed-d639efe7edc2.png">

**Comment by pmachowski** [comment]
@basarat whats the theme/syntax theme used in your screenshots?

**Comment by basarat** [comment]
I now use Monokai. In fact I believe in Monokai or death 🌹:)
