### ISSUE TITLE
Syntax highlighting fails after line 245

### ISSUE THREAD

**Issue by jikanter** [TypeStrong/atom-typescript#623]
Syntax highlighting fails after line 245. Issue occurs mid-datastructure, works fine when I drop the next string to the next line
![untitled](https://cloud.githubusercontent.com/assets/825376/10146432/72833bd4-65ee-11e5-8c13-a93ead4027ee.png)

**Comment by jikanter** [comment]
My apologies, column 245.

**Comment by basarat** [comment]
@jikanter can you paste that line here. It would help with the repro :rose:

**Comment by basarat** [comment]
I did a quick test and it worked fine : 

![image](https://cloud.githubusercontent.com/assets/874898/10152980/10127728-669b-11e5-9c52-c116c656485a.png)

Note that grammar has been behaving weird since atom `1.0.16`. Details here : https://github.com/TypeStrong/atom-typescript/issues/611 so this might be because of that

But do provide the line for record / testing :rose:

**Comment by jikanter** [comment]
will do, here is the line
```TypeScript
'input': [GlobalAttributes.concat('accept', 'alt', 'autocomplete', 'autofocus', 'checked', 'dirname', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'height', 'list', 'max', 'maxlength', 'min', 'minlength', 'multiple', 'name', 'pattern', 'placeholder', 'readonly', 'required', 'size', 'src', 'step', 'type', 'value', 'width')],
````

Thanks!

**Comment by basarat** [comment]
Error exists in `language-grammar` as well so created an issue there to get more (smarter) :eyes: https://github.com/atom/language-javascript/issues/229

**Comment by basarat** [comment]
Hoping for an upstream fix :+1:

**Comment by basarat** [comment]
Its an atom limitation at the moment, only :100: tokens allowed per line. Subscribe here for details : https://github.com/atom/atom/issues/1667 

:cry:
