### ISSUE TITLE
pending requests for excluded files

### ISSUE THREAD

**Issue by yoorek** [TypeStrong/atom-typescript#657]
(7.4.1) Compiler is kicked off with error for files in excluded folder and there are lots of pending requests.

I excluded 'dist' folder but after editing /dist/main.d.ts and saving:
- compiler tries to compile it which (why? it's excluded by filesGlob and exclude)
- error 'The xxx file is not included in compilation context.....' - if it's not included than why compile it?
- there are > 50 pending requests

Here is my tsconfig:

``` json
{
    "compilerOptions": {
     ....
       "declaration": true,
        "outDir": "dist"
    },
    "filesGlob": [
        "ts/**/*.ts",
        "typings/tsd.d.ts",
        "!dist/**",
        "!node_modules/**"
    ],
    "exclude": [
        "dist", "node_modules"
    ], 
   "files" : [......]
}
```

**Comment by nycdotnet** [comment]
If you have a `files` element, then `exclude` is ignored.  See the fourth bullet here: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#details

The error "not included in the compilation context" is not really an error.  It's just sort of just an FYI that if you did want this file to be compiled then it wouldn't be.  We should probably have a better visual experience for it.  Are you sure atom-typescript actually tried to compile it?  I don't know how that would work since the language service needs it to be in context in order for it to compile, and there wouldn't be an emit for a d.ts file anyway.

**Comment by yoorek** [comment]
I know 'exclude' should be ignored but tried to keep it anyway - thought atom-typescript could use it.
And the error 'not included' does not bother me. The problem is that 'atom-typescript' tries to compile it on Save even if it should't AND it does it in the way that lots of files ends up in the queue.
Look at screenshot just after hitting CMD-S on empty d.ts file which is not on 'files' list (68 files in queue and they hang till Atom shutdown)


<img width="1440" alt="zrzut ekranu 2015-10-13 o 20 05 27" src="https://cloud.githubusercontent.com/assets/271500/10463645/00de9fba-71e6-11e5-8ae5-c781ca6d6ebe.png">
