### ISSUE TITLE
Non-standard tsconfig.json keys, group under atom-typescript key?

### ISSUE THREAD

**Issue by Meligy** [TypeStrong/atom-typescript#662]
I noticed the key `externalTranspiler` (https://github.com/TypeStrong/atom-typescript/pull/475) in the FAQ and was very happy about it. It got me quite confused when I ran `tsc` from terminal though I got different results

So, you see, this is an awesome feature (and I really mean it), but it introduces confusion, because its using what looks like TypeScript configuration `tsconfig.json`.

Would it make sense to move the keys like `externalTranspiler` under a new root key like `atom-typescript`?

It would also apply to options (https://github.com/TypeStrong/atom-typescript/issues/521), and any other non tsc keys.

**Comment by basarat** [comment]
This has been discussed before. But its a breaking change that isn't planed in the near future. Sorry :rose:

**Comment by Meligy** [comment]
Is it possible to consider a depreciation cycle?

Deprecate the old option for a release or 2 and encourage users to move to the new keys, and eventually kill the old keys?

Thanks a lot.

**Comment by basarat** [comment]
There is a concern about making these features locked into atom-ts, e.g. `filesGlob` is fairly widely supported (because it is something that really should be in tsconfig to begin with). 

See previous discussion : https://github.com/TypeStrong/atom-typescript/issues/594#issuecomment-143870478 :rose:
