### ISSUE TITLE
autocomplete for ts npm modules not updated after change this npm module

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#665]
Hello @basarat! 
I created ts npm module and use it in ts project.
After change npm module i need restart atom for update autocomplite in consumer-ts-file.

**Comment by basarat** [comment]
> i need restart atom for update autocomplite in consumer-ts-file.

Probably because `npm install` is external to atom and we don't do any fancy directory watching. Try sync : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#atom-typescript-is-complaining-about-not-finding-files-or-other-weird-errors

If that doesn't work we can discuss further :rose: Closing for now.

**Comment by stepancar** [comment]
@basarat, sync not working.
If you change any typescript file and then try to select autocomple in consumer code - you can see autocomple is in actual state, but if changed ts npm module - autocomple will not updated

**Comment by basarat** [comment]
> but if changed ts npm module - autocomple will not be updated

And sync doesn't fix this? Is there a `.d.ts` file in the npm module that *should be updated but didn't get updated*. Note that ts at the moment works best if the npm module has a `.d.ts` file generated :rose:
