### ISSUE TITLE
jsx highlighting breaks if text in span contains key words of typescript

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#666]
Hello!
this screen demonstrate this issue
![screenshot_7](https://cloud.githubusercontent.com/assets/2854910/10541215/ecfff942-7417-11e5-914a-28900d6b7999.png)
Thank you!

**Comment by basarat** [comment]
Sample :rose: 

```jsx
let x = <div>
    I do declare that this is a bug
</div>
```

![image](https://cloud.githubusercontent.com/assets/874898/10549613/e2de7954-748d-11e5-961f-30463db6eb56.png)

**Comment by nycdotnet** [comment]
Good show old chap!

**Comment by stepancar** [comment]
@basarat, maybe you can help me with this issue. I dont know how to fix it, and how to find reason of this behavior. But i wanna help. Thank you.

**Comment by basarat** [comment]
> dont know how to fix it, and how to find reason of this behavior. But i wanna help. Thank you.

# Basic 

The issue is that the `tsx` grammar is breaking into `ts` in a string literal. 

# Further info

This is the grammar file : https://github.com/TypeStrong/atom-typescript/blob/master/grammars/tsx.cson which is a shameless copy of atom-react ([current code](https://github.com/orktes/atom-react/blob/249e0fab8e540d55ed84a13b41c7aa9518146655/grammars/JavaScript%20(JSX).cson)). If the bug exists here there is probably a bug upstream and worth reporting to https://github.com/orktes/atom-react/issues (or check if its already there) so that we get more :eyes: on it. 

Also  @Cu3PO42 is the resident grammar expert so one can direct questions for him :rose:

Also I have some docs linked here : https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md :rose:
