### ISSUE TITLE
Reuse Grammars from Sublime-TypeScript

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#675]
From https://github.com/TypeStrong/atom-typescript/pull/672, we should investigate if a simple npm script can be utilized to copy and repackage the grammars from Sublime.

## edits by @basarat: 

We have very little custom work ... 

* The top that needs to be preserved across versions: https://github.com/TypeStrong/atom-typescript/blob/729b5522cc17fc84511c05ebb5ae1812f3ec4b00/grammars/typescript.cson#L12-L80

* The angular template support
https://github.com/TypeStrong/atom-typescript/pull/798

**Comment by stepancar** [comment]
@blakeembrey, I think we should ask typescript team. Maybe they have any plans to export/support typescript grammar as any external module.
Can you [ask](https://github.com/Microsoft/TypeScript/issues), please? I don't know how to ask correctly.
Way when we just copy grammars from sublime is not good, i think

**Comment by blakeembrey** [comment]
@stepancar I think it's worth investigating from the Atom side first too. If we can just convert it with a script, there's no need for a separate module or special support. As for them publishing an external module, I don't have any ideas on the format of how that would look - I haven't had enough exposure to various IDE language definitions to know if it's simple to publish a common denominator (or maybe generate each of them?).

**Comment by stepancar** [comment]
@blakeembrey i created [issue](https://github.com/Microsoft/TypeScript/issues/5356)
join to discussion :)

**Comment by blakeembrey** [comment]
:tada: It's done. We should be investigating this soon, would be easy enough to use a script to convert into the format Atom uses. It looks like they're going to add a testing framework too, so that sounds like a huge win against maintaining the grammar here.

**Comment by sgal** [comment]
@blakeembrey As far as I see, those grammar files are just imported from Sublime Text package, so it's not a "real" TS grammar from MS. See https://github.com/Microsoft/TypeScript-TmLanguage/issues/1

We indeed should track the progress there, but I guess it's too early to integrate it here.

**Comment by quadrophobiac** [comment]
@blakeembrey I arrived here after indicating interest in one of the separate tickets (#707) prior to it's collation here by the recent mass assignment of 'up-for-grabs' labels. I read from your comment https://github.com/TypeStrong/atom-typescript/issues/675#issuecomment-154325788 that you are following the 'copy via script' rather than 'investigating from Atom first principles' option on this - did I understand that correctly? Does that mean that these are or are not still 'up-for-grabs' style issues?

**Comment by blakeembrey** [comment]
@quadrophobiac Absolutely up for grabs, if you want to give it a shot I'll review the PR. I'm not currently working on this. Not sure what you meant copying rather than investigating Atom first principles?

**Comment by quadrophobiac** [comment]
Hey, I was referring to the chain of correspondence in previously when you said  
> I think it's worth investigating from the Atom side first too.

and then  
>It's done. We should be investigating this soon, would be easy enough to use a script to convert into the format Atom uses. 

As I understand it the task is to create an Atom native grammar rather than a repurposed sublime grammar?

You also mentioned
>It looks like they're going to add a testing framework too, so that sounds like a huge win against maintaining the grammar here.

I'm inferring that this is a test specification for .ts coming from MS - is that right?

I'll get a dev instance of the repo up and running in the meantime

**Comment by blakeembrey** [comment]
@quadrophobiac All the grammar will come from the TypeScript sublime text side, we should only be converting it. The Atom side comment is exactly the same now as before, it's not a universal grammar so there's still conversion we need to do. In the original context, it was in response to opening an issue and moving everything prematurely (before we know what we're doing with it) but that's already happened now.

**Comment by quadrophobiac** [comment]
Ah ok got it!

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v8.0.0 :rose:
