### ISSUE TITLE
Name property for function

### ISSUE THREAD

**Issue by avarices** [TypeStrong/atom-typescript#688]
Currently the below code is seen as incorrect by you guy's package, but the code runs just fine. As far as I know the following code has worked since node.js 4.0, maybe even node.js 0.12.x. I'm not entirely sure because I was using io.js for a while and it's always had that feature for as long as I used it but, after moving to typescript and node.js 4.0 it seems maybe nodejs 0.10.x didn't have the all of the features it does now. 

    class MyClass {
       constructor() {
       }
    }

    let variable: MyClass = new MyClass()
    console.log(variable.constructor.name)

The error is on the last line of code, it says `Property 'name' doesn't exist on type Function`
If you run the code it will work just fine though. It logs `MyClass`, just like it should so, hopefully this can be fixed soon? Thanks for reading the issue.

**Comment by blakeembrey** [comment]
@avarices This is an issue with the type definition you're using. Since `Function.prototype.name` wasn't 100% standard, it's not included in the TypeScript `lib.d.ts` file. You'll need to add this to the type definition to work out of the box, or coerce the variable using TypeScript.

Reference: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L229-L258

You can also do:

```ts
console.log((<any> variable).constructor.name)
```

**Comment by basarat** [comment]
> If you run the code it will work just fine though. It logs MyClass, just like it should so, hopefully this can be fixed soon

depends on where you run it. Don't run it on IE :rose:

![image](https://cloud.githubusercontent.com/assets/874898/10775736/14ab2eb2-7d5f-11e5-8c43-4c21fb9243ef.png)
