### ISSUE TITLE
error window overlaps cursor position

### ISSUE THREAD

**Issue by kaffeebaum** [TypeStrong/atom-typescript#699]
If I am editing a line near the bottom of the screen, the error window that pops up hides the line that I am currently editing. Is there some setting to fix the height of the error window at the bottom?

![atom](https://cloud.githubusercontent.com/assets/15579350/10871333/5a76029a-80e4-11e5-9a83-e3fc10eaf876.gif)

**Comment by basarat** [comment]
> The error window that pops up hides the line that I am currently editing

There are two issues here ... Our *error summary* and the error list from atom/linter https://github.com/atom-community/linter.

![image](https://cloud.githubusercontent.com/assets/874898/10871775/9db6adc4-8144-11e5-8c9d-be88b2bf318d.png)

**LINTER** Click on `file` to toggle it so that it doesn't expand on typing. Let us know if its unclear :rose:



**OUR** For our error summary: @blakeembrey its because we split the error summary to show on new line for small screen. Can I we just keep it *highly trimmed* and near useless on the same line?

**Comment by kaffeebaum** [comment]
"Disabling" the linter worked fine, it makes the situation already a lot better.
