### ISSUE TITLE
running `grunt` on atom-typescript-> JSX-related issues and more

### ISSUE THREAD

**Issue by laurelnaiad** [TypeStrong/atom-typescript#746]
I'm trying to build atom-typescript locally.

Did I miss some steps in configuring my environment or the local repo?

Things I did:

* `npm install`
* `npm install grunt` (why wasn't this in the package.json as a dev dependency?)
* `npm install grunt-ts` (ditto?)

```bash
$ grunt
Running "ts:dev" (ts) task
Watching all TypeScript / Html files under : lib
Compiling...
### Fast Compile >>lib/globals.ts
### Fast Compile >>lib/linter.ts
     <lots of Fast Compiles snipped>
### Fast Compile >>lib/worker/parent.ts
### Fast Compile >>lib/worker/queryParent.ts
Using the custom compiler : ./node_modules/ntypescript/bin/tsc
lib/main/atom/views/rView.tsx(34,16): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
lib/main/atom/views/semanticView.tsx(101,16): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
lib/main/atom/views/semanticView.tsx(107,16): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
lib/main/atom/views/semanticView.tsx(109,13): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
lib/main/lang/transformers/transformer.ts(2,28): error TS2307: Cannot find module 'source-map'.
lib/main/tsconfig/tsconfig.ts(210,27): error TS2307: Cannot find module 'tsconfig'.
```

**Comment by basarat** [comment]
> npm install grunt (why wasn't this in the package.json as a dev dependency?)

Because it broke atom package installer at some point : https://github.com/TypeStrong/atom-typescript/issues/600 

Don't use grunt. Sadly you need atom-typescript to build atom-typescript as is documented here : https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#workflow Probably should be more up in the guide :-/ I'll move it around and then close this issue :rose:
