### ISSUE TITLE
Errors In Open Files only updates when the tab is active

### ISSUE THREAD

**Issue by adamduren** [TypeStrong/atom-typescript#761]
My "Errors In Open Files" only updates when I switch to the tab with an error. For example. If I remove a parameter from a base class method and the child calls the super. The child file only shows that it has an error when it is made the active tab instead of when I remove the parameter from the base class.

Any ideas?

**Comment by basarat** [comment]
> The child file only shows that it has an error when it is made the active tab instead of when I remove the parameter from the base class.

This is by design. We *query* the errors *only for the current file* when:

* the file contents change
* the active tab changes

This works fine in most cases and results in less inconsistency... at least you never end up wondering if there is an error or not because some background magic is happening. It integrates well with *edit as you go* behavior (and low overhead) which is desirable with general purpose TS editing.

# More 

A background worker that actively maintains project state + evaluates all errors would be possible if we work on *Active Project* concept. That's what I'm going with the next *not ready* project : https://github.com/TypeScriptBuilder/tsb

**Comment by adamduren** [comment]
@basarat Thank you for the explanation.
