### ISSUE TITLE
Can import autocompletion not insert semicolon?

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/atom-typescript#806]
I don't really use semi-colons, can we detect this on the line and if a semicolon is missing skip inserting it?

**Comment by basarat** [comment]
> I don't really use semi-colons

Now I don't feel so bad about my lack of using them sometimes (or maybe I should be cause that means I'm inconsistent). Up for grabs :rose:

# Implementer guidance

Recently work was done to make import autocomplete preserve whitespace. Similar approach should be taken here : https://github.com/TypeStrong/atom-typescript/pull/805 :rose:

**Comment by blakeembrey** [comment]
FWIW, I love that you do this :+1: You leave fantastic comments for the next person to come along!

**Comment by ApricumMedia** [comment]
A +1 from me, it should preserve every allowed code style. The auto-complete system could either read an existing linter style or use a `style` option from the `tsconfig`.

**Comment by lierdakil** [comment]
@ApricumMedia, there is no `style` option in `tsconfig`, is there? https://www.typescriptlang.org/docs/handbook/compiler-options.html

Besides, since we're using `tsserver`, for autocompletion, built-in formatting, etc, I feel like this issue belongs to the TypeScript repo, and hey, look, [here it is](https://github.com/Microsoft/TypeScript/issues/19882).

Also, to be fair, we do support non-standard `formatCodeOptions` setting in `tsconfig.json`. It doesn't support semicolon behaviour configuration though.

For the sake of completeness, here is the schema of `formatCodeOptions` (taken from `tsserver` protocol description, may change depending on your TypeScript version):

```ts
    interface FormatCodeSettings {
        baseIndentSize?: number;
        indentSize?: number;
        tabSize?: number;
        newLineCharacter?: string;
        convertTabsToSpaces?: boolean;
        indentStyle?: "None" | "Block" | "Smart";
        insertSpaceAfterCommaDelimiter?: boolean;
        insertSpaceAfterSemicolonInForStatements?: boolean;
        insertSpaceBeforeAndAfterBinaryOperators?: boolean;
        insertSpaceAfterConstructor?: boolean;
        insertSpaceAfterKeywordsInControlFlowStatements?: boolean;
        insertSpaceAfterFunctionKeywordForAnonymousFunctions?: boolean;
        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis?: boolean;
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets?: boolean;
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces?: boolean;
        insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces?: boolean;
        insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces?: boolean;
        insertSpaceAfterTypeAssertion?: boolean;
        insertSpaceBeforeFunctionParenthesis?: boolean;
        placeOpenBraceOnNewLineForFunctions?: boolean;
        placeOpenBraceOnNewLineForControlBlocks?: boolean;
    }
```

In the meantime, consider using some sort of 'save-on-prettify' tool with the prettifier you like. We're using prettier and found it to be rather nice.

**Comment by finscn** [comment]
any news?
