### ISSUE TITLE
Package option: format on save

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#81]
Title is self explainatory

We will make the default true later but not now due to bad formatting done by the current compiler in certain cases. Try `v1.4.2`.

**Comment by claudio-silva** [comment]
What do you mean with "plugin option"? Does `atom-typescript`have plugins? Or are you referring to the main package?
If so, please do not force autoformatting of code. Some people will really NOT like that someone or something messes up their code! ;-)
I, for instance, used to use Webstorm autoformatting with very specific settings to get the format just the way I like. It's not easy to replicate that on other formatting tools, as Webstorm has so many ways / rules to customize the formatting. That's why I'm considering writing my own autoformatter.
I would be fine with a configurable setting on the Settings for your package, though.

**Comment by basarat** [comment]
> plugin option

fixed title.

> If so, please do not force autoformatting of code

cool. Will leave default as false.

> , as Webstorm has so many ways / rules to customize the formatting

We expose formatting options exposed from the language service. Have a look at : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#format. We support them on *per project* so it might be useful to share with your team and then everyone checks in similarly formatted code if you enable auto format on save.  See if these options meet your requirement. I'd be interested to know if there are options you want but don't see.

**Comment by claudio-silva** [comment]
Thanks! I'll try it and then I'll give you some feedback.
Just to clarify:
> I would be fine with a configurable setting on the Settings for your package, though.

I was referring to an option to format on save.

**Comment by fd** [comment]
@basarat any news on the _format on save_ option?

**Comment by basarat** [comment]
Still conflicted mentally between making it a package option or an option in tsconfig (I really want it to be in tsconfig) ... @fd do you have an opinion on where you would like this? 

FWIW we have `buildOnSave` and `compileOnSave` in tsconfig

**Comment by fd** [comment]
I think `formatOnSave` in tsconfig is probably the best option. This way it is consistent with the other `OnSave` settings.

**Comment by basarat** [comment]
> I think formatOnSave in tsconfig is probably the best option. This way it is consistent with the other OnSave settings.

:+1: Up for grabs for now, unless I feel the need for it. Note that autoformatting `jsx` elements was a bit broken at the moment in Microsoft/TypeScript last I checked, so I'm not doing this as a quick win for now.

**Comment by lordmat0** [comment]
#810 implemented this so this can be closed.

**Comment by basarat** [comment]
🌹🌹
