### ISSUE TITLE
*This* in constructor error

### ISSUE THREAD

**Issue by allenRoyston** [TypeStrong/atom-typescript#821]
Maybe this isn't an error, but I can't seem to get around this particular issue.  How do I declare *this* without it producing an error?  When it compiles it's fine but that error continues to show up.  Any suggestions?

![screenshot from 2016-01-20 16 45 50](https://cloud.githubusercontent.com/assets/7491856/12468119/b14ad088-bf95-11e5-88bf-8aeefb437bfd.png)

**Comment by basarat** [comment]
all member of classes need to be declared. This is to protect you from typos. 

```ts
name:string
constructor(){
    this.name = 'foo'
}
```

Would be great if you use stackoverflow for this. I help there a lot : http://stackoverflow.com/tags/typescript/topusers :rose: 

> When it compiles it's fine but that error continues to show up

Just because it compiles to JS doesn't mean its error free: https://basarat.gitbooks.io/typescript/content/docs/why-typescript.html :rose:

**Comment by allenRoyston** [comment]
I know I'm a few weeks late, but I just wanted to thank you for getting back to me.  This totally fixed it and I felt dumb immediately aftewards lol.  Thanks again!
