### ISSUE TITLE
tsconfig : postbuild seems to be not working

### ISSUE THREAD

**Issue by taraknaira** [TypeStrong/atom-typescript#841]
I am trying to trigger some action after successful build. I have tried as mentioned below

https://github.com/aspnet/Home/wiki/Project.json-file#scripts

But nothing is happening. Looks like there is an issue with below line parent.ts

exports.build = catchCommonErrors(parent.sendToIpc(projectService.build));

If I remove everything and simply place 

exports.build = projectService.build;

then it is working fine. Not sure about the root cause.

FYI, I am using version 8.2.0

**Comment by LongHairedHacker** [comment]
I can confirm this.

Either it does not work at all, or the documentation is wrong and therefore I can't get it to work.
I'm trying to use it to run browserify on some of my modules.

````
  "scripts": {
    "postbuild": "browserify -o browser/libsil.js js/libsil.js"
  },
````
But nothing happens.
I'm using 8.2.0 as well.

**Comment by LongHairedHacker** [comment]
I did some digging and found out that my call to browserify fails for some reason,
but the error is never propagated anywhere useful.

The code in [projectService.ts 135](https://github.com/TypeStrong/atom-typescript/blob/67e6a03588f7294f032a9cc25e6a7c909351ae9a/lib/main/lang/projectService.ts#L135) simply dumps it to the developper console.

I'm still tying to understand why the call to  browserify fails with stderr:
````
Error: ENOTDIR: not a directory, open '/usr/share/atom/resources/app.asar/package.json'
    at Error (native)
````

Maybe there is something off with the working directory.

**Comment by LongHairedHacker** [comment]
After some more investigating it turned out that NODE_PATH and NODE_ENV are set to atoms node interpreter and environment for anything executed as postbuild action.
As a result my browserify fails to retrieved the package.json file mentioned in the error message.
This might actually be worth fixing or at least being mentioned in the documentation for postbuild.

As a workaround I used a bash script as postbuild action, that unsets NODE_PATH and NODE_ENV.
Now everything works as expected.

**Comment by nycdotnet** [comment]
In the docs for Child_Process, it appears we can set particular variables for the environment.

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

I don't have access to a Mac/Linux box to test this (bad person) - any chance you're willing to try that?

**Comment by nycdotnet** [comment]
This may be the relevant code:
https://github.com/TypeStrong/atom-typescript/blob/master/lib/worker/lib/workerLib.ts#L230

**Comment by LongHairedHacker** [comment]
Options ``` env : {} ``` give me a set of environment variable that is okayish.
At least  NODE_PATH and NODE_ENV are no longer set.

Unfortunately there is still one problem. 
It gives me different PATH then my shell sessions do.

On a shell I get:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
Which is the default case under Archlinux as far as I can tell.

Using env : {} I get:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
```
Also a few other variables that are set in the environment of the shell are completly gone.

So it solves the problem I reported above as I can now run browserify,
but it will break as soon as somebody tries to run something that relies on a directory being added to the users PATH.
For example rvm adds stuff like ```/home/rincewind/.rvm/gems/ruby-2.0.0-p247/bin```
to your PATH variable, to allow you to easily run things in that particular virtual environment.

I'm not really sure which kind environment I should expect when running thing from inside my editor.
Usually programs started by my desktop have the same environment as my display manager, which has the same as my shell.
So I'd probably expect the same environment variables  as the shell I started atom in.

But once again I'm not entirely sure what I should except.

**Comment by LongHairedHacker** [comment]
I just tried build my project on a different machine that runs ubuntu instead of arch linux.
There the postbuild action does not seem be executed at all.
Which seem to be similar to what @tarak162 encountered.

So to summarize my current observations:

Ubuntu 14.04.4
Atom 1.5.3
atom-typescript 8.2.0
**Does not execute postbuild at all.**

Arch Linux
Atom 1.5.3
atom-typescript 8.2.0
**Executes postbuild, with wrong environment.**

**Comment by nycdotnet** [comment]
On the atom-typescript plugin settings page there is a checkbox that says "Debug: Atom-TypeScript. Please do not use."  :smiley:   I am giving you permission to check that box and then quit atom altogether and then reload it.  Does the postbuild work with that checked on either environment?  I believe that one of the changes that checkbox brings is running the TypeScript worker in the same process as atom itself.

**Comment by LongHairedHacker** [comment]
It took me a while to get back to the ubuntu machine to some more testing.
I must have been doing something wrong last week, since now the ubuntu machine behaves in the same way then my arch linux machine, even without having the checkbox checked.

So sorry for that, must have been my mistake somehow.

**Both systems run the postbuild script.**

Still NODE_PATH and NODE_ENV are set to atoms node interpreter on both machines.
Also regardless of the setting of the checkbox.
