### ISSUE TITLE
There is no highlight when I cut "import from" to multi-line

### ISSUE THREAD

**Issue by alexsunxl** [TypeStrong/atom-typescript#847]
this is situation I encountered
<img src="http://7xj9do.com1.z0.glb.clouddn.com/2016-02-12-14552106324530.jpg" />

**Comment by basarat** [comment]
Here https://github.com/TypeStrong/atom-typescript/blob/0970dc01caa17bbbd1d36a9ad6176f39f468eed9/lib/main/atom/autoCompleteProvider.ts + needs proper tokenization in the grammar https://github.com/TypeStrong/atom-typescript/blob/0970dc01caa17bbbd1d36a9ad6176f39f468eed9/scripts/grammar.js

**Comment by blakeembrey** [comment]
Just a note, but I tried for a while to support this but it's a giant PITA to make work. Ideally, the part between `import ... from` would be an expression and the string a string expression. However, I couldn't match it correctly because of my limited Textmate grammar experience (I couldn't find anyway it's possible) and keeping compatibility with the current grammar (which is used by `atom-typescript` to provide autocompletion of paths - probably a past mistake to couple the grammar with that, but it's already done).

**Comment by basarat** [comment]
> probably a past mistake to couple the grammar with that, but it's already done

Agreed. Ideally one would modify this endpoint https://github.com/TypeStrong/atom-typescript/blob/1f311a4a41ad53a109a572256d2ae0e269d23a95/lib/main/lang/projectService.ts#L181 but I hear MS/TypeScript is doing that anyways since its needed badly by VSCode :rose:

**Comment by alexsunxl** [comment]
@blakeembrey   :rose:

**Comment by RomanGotsiy** [comment]
Works fine for me on the latest version `11.0.3`:

![image](https://cloud.githubusercontent.com/assets/3975738/25795162/cfbde91c-33dc-11e7-9b4e-19f7717d663c.png)

Maybe should be closed
