### ISSUE TITLE
TODO Highlight for inline comments

### ISSUE THREAD

**Issue by suppayami** [TypeStrong/atom-typescript#848]
I'm using this pakage for my development, and notice that TODO Highlight only works with block comments, for inline comments like **// TODO: ABC**, it won't work.

This is the screenshot: http://puu.sh/n5hvu/dae2fe49fb.png

**Comment by sharpmachine** [comment]
Same here. Would be nice for it work with `//`

**Comment by adambuczynski** [comment]
See this comment for reference on how to fix this: https://github.com/atom/language-todo/issues/33#issuecomment-228630076

**Comment by olee** [comment]
Would be really great if this could be addressed quickly (as it looks easy to fix according to the link).

**Comment by googol7** [comment]
+1

**Comment by olee** [comment]
I just tested it - replacing [this](https://github.com/TypeStrong/atom-typescript/blob/master/grammars/ts.cson#L1019-L1021) with the following works
````
  "comment-line":
    name: "comment.line.ts"
    begin: "//"
````

**Comment by olee** [comment]
I fixed the previous post with the correct grammer config.
With that it properly recognizes TODOs in TS files.

**Comment by dsifford** [comment]
@olee Did you open a PR with that fix? If not, can you?

**Comment by olee** [comment]
*OT: Why does everyone on open source projects always want reporters to make PRs instead of just integrating the fix themselves as maintainer? :expressionless:*

Sorry, but I'm quite short on time currently so it would be nice if someone else could make a PR (or directly commit to the project if it's a developer).

**Comment by cortopy** [comment]
I don't understand why all the fuss with this issue. Just created a PR with @olee code. It works in my local version

**Comment by dsifford** [comment]
@olee If you're referring to me: I'm not a maintainer.

**Comment by googol7** [comment]
the source of the problem is in TypeScript-TmLanguage and shall be solved there imho. made a pull request there: 

https://github.com/Microsoft/TypeScript-TmLanguage/pull/222

**Comment by cortopy** [comment]
thanks @googol7 looks great

**Comment by googol7** [comment]
The problem should now have been solved with this PR https://github.com/Microsoft/TypeScript-TmLanguage/pull/257 See also this issue: https://github.com/Microsoft/TypeScript-TmLanguage/issues/181

**Comment by googol7** [comment]
Finally this issue has been resolved with release [v10.1.8](https://github.com/TypeStrong/atom-typescript/releases/tag/v10.1.8)

**Comment by adambuczynski** [comment]
Good news, one down, but still many to go :(
The TS language package is so far behind JS language it's a bit depressing to work in TypeScript 😢

**Comment by Nxt3** [comment]
This still hasn't been fixed for me running v11.0.1

**Comment by AJStacy** [comment]
I'm still experiencing this bug in v13.1.0

**Comment by lierdakil** [comment]
First of all, we don't ship our own grammar any more because Atom does. See https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#syntax-highlighting-is-bad

Notice that if you're using tree-sitter grammars (if you're not sure, on newest Atom versions you most certainly do), those are not downstream from [Microsoft/TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage), but are developed separately by Atom team in [tree-sitter/tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript). And it's a known issue that TODO thingamajig doesn't work with tree-sitter parsers, see https://github.com/atom/atom/issues/18467 https://github.com/atom/atom/issues/18196.
