### ISSUE TITLE
Parse Markdown in tooltips

### ISSUE THREAD

**Issue by RichardForrester** [TypeStrong/atom-typescript#865]
Comparing tooltips on different editors. I really like atom and atom-typescript, but looking at the way VS Code renders tooltips that are written in markdown, it's just a lot better. 

As you can see, the markdown tooltips for libraries such as Immutable.js are just being passed through with no formatting applied:
<img width="1440" alt="screen shot 2016-02-25 at 5 19 34 pm" src="https://cloud.githubusercontent.com/assets/12902182/13342340/a326ba38-dbe4-11e5-8741-f24ce8e751bd.png">

However, the same tooltip on VS Code is rendered as intended and I'm sure you'll agree, it's a lot better experience:
<img width="1440" alt="screen shot 2016-02-25 at 5 19 12 pm" src="https://cloud.githubusercontent.com/assets/12902182/13342341/a32a8352-dbe4-11e5-9b59-15c9e2fad8d2.png">

**Comment by chharvey** [comment]
Here is a comparison of tooltips (“datatips”) from `atom-typescript` (top) and `ide-typescript` (bottom). On the top, I like that the method signature wraps to the next line instead of making me scroll, but on the bottom I like the Markdown formatting, the sans-serif font, and the JSDoc/TypeDoc tags (e.g. `@param`) are helpfully shown.

<img width="649" alt="screen shot 2019-01-21 at 10 42 24" src="https://user-images.githubusercontent.com/1362083/51485184-6eda0980-1d6b-11e9-81eb-6e184414427b.png">
