### ISSUE TITLE
Closing constructor curly bracket will cause highlight issues

### ISSUE THREAD

**Issue by Fank** [TypeStrong/atom-typescript#884]
If you align the closing constructor curly bracket the highlight will break:
![screenshot from 2016-03-14 18-28-51](https://cloud.githubusercontent.com/assets/1900106/13753340/dac591da-ea12-11e5-9d66-ec857fbaf217.png)

If you place the bracket behind the last parameter everything works fine:
![screenshot from 2016-03-14 18-29-13](https://cloud.githubusercontent.com/assets/1900106/13753398/103ee85c-ea13-11e5-9669-e3619102095b.png)

**Comment by Bifros7** [comment]
I would like to see this fixed too.

**Comment by Fank** [comment]
Its a problem with the Decorator/Annotations, if you remove them everything works fine

**Comment by nycdotnet** [comment]
Hi,

Thank you for the report.  Sorry it took so long to reply.

The atom-typescript plugin uses a grammar that is maintained by Microsoft.  Please report this issue here: https://github.com/Microsoft/TypeScript-TmLanguage/issues

If/when the issue is fixed there, please let us know and we will pull down the latest grammar.

Thanks.

**Comment by guncha** [comment]
Looks like it's fixed to me. Let us know if you see otherwise.
