### ISSUE TITLE
Multiple Project Support

### ISSUE THREAD

**Issue by basarat** [TypeStrong/atom-typescript#910]
> Note : Leaving this purely as a documentation, and potential idea for exploration by any TypeStrong / community member 
# How tsconfig.json detection works now.

We have a file/class called `Project` which basically consolidates all our access to the TypeScript language service ([the code](https://github.com/TypeStrong/atom-typescript/blob/ae66fbbba503aaa2329209421f3362a35f89127c/lib/main/lang/core/project.ts)). 

When you open a `.tsx?` file in the editor we lookup some `tsconfig.json` up the directory tree. If we find one we
- read it
- convert it to a project
- for all the files identified as a part of the project we create a hot cache so we share the same project for queries against these files. 

([here is the code](https://github.com/TypeStrong/atom-typescript/blob/ae66fbbba503aaa2329209421f3362a35f89127c/lib/main/lang/projectCache.ts))
# Issues with this

If you have several tsconfig.json files in your project, e.g.:
- server/tsconfig.json
- client/tsconfig.json

The tsconfig files also reference some shared files in:
- src/shared.

If you open a file from `server` _first_ then all the files referenced (including `shared`) will point to that `server/tsconfig.json`. Then even if you update `client/tsconfig.json` it will have seemingly _no_ effect on any file that the editor opens (as they all already point to `server/tsconfig.json`). 
# Potential fixes
## Project selector

This is the approach I am taking with http://alm.tools/ . It features a `project` search/selector : https://github.com/alm-tools/alm/tree/master/docs/features#project-search + ability to provide a project on the command line (`-p` flag). 

It is less magical then what atom-typescript does, but then again atom-typescript was designed to be as quick to start / unobtrusive as possible i.e. you open a ts file and it _just works_. 

alm.tools is designed to be _for typescript alone_. You _need_ a project file. 
## Multiple simultaneous projects

This is the approach taken by VSCode / TSServer (that comes with `typescript` out of the box). 

However there are issues with this design too e.g.:
- autocomplete can end up with duplicates and deduplication needs to happen
- rename refactoring needs to take place across all the code base / projects. 

All of these complex scenarios are being fixed in TSServer by the Microsoft team (:rose:) and if this is the approach that needs to happen I recommend that current code be pulled out and migrate to TSServer. This will result in feature decrease (e.g. dependency view) but might be better in the **long** term :rose: 
# Personal opinions

What I did with atom typescript isn't ideal for sure and it would be better if it takes one of the mentioned approaches. Please note that I did this _before_ tsserver was a thing so `¯\_(ツ)_/¯`, and because of (again) ambitious plans of https://alm.tools it does something custom (doesn't use tsserver again as [I find my work on async support easier personally](https://github.com/alm-tools/alm/blob/master/docs/contributing/ASYNC.md), also haven't had the time to take a hard look at TSServer) :rose: :heart:

**Comment by psnider** [comment]
Here is a method I found that works for me 
when I want to switch the atom-typescript project-focus to a new tsconfig.json:

- Select a file that is referenced by the filesGlob pattern in the tsconfig.json that you want to use.  
This file must be located within or below the directory that contains the tsconfig.json file.  
If the file path requires a relative reference **../**
then the tsconfig.json won't be found.
- Save the file, or run sync from within it ( **⌘ '**   command+single-quote on mac)

**Comment by laurelnaiad** [comment]
I think about this subject from time to time.

My thoughts generally lead to a supposition that if atom-typescript's worker were based on the identification of a set of tsconfig files as its "drivers" (instead of having the editor window be the driver), that the process of identifying which project(s) include a given .ts (or now also .js) file would be more straightforward.

And, given that tsconfig files no longer need to be named tsconfig.json, it seems pretty obvious that somebody's now got to maintain or infer a list of them.

I know there's a lot more going on, because I've seen some of it and actually learned a bit of it, but I believe the process now is something like "I seem to be handling a ts file, let me findup for a tsconfig that includes this file", it would be, 'I seem to be handling a ts file, let me check my tsconfigs to see which projects (note the plural) include this file'.

Regarding the circumstance where more than one project includes the file, it seems to me that the only correct response is to process it under both regimes in parallel.

In psuedo code, I'm talking about:

```
errs: []
tsconfigs; WorkspaceTsConfigsList
with(.ts file) {
  tsconfigs.where(tsconfig.includes(file)).build(file)
  .onSuccess(report green)
  .onErr(err => errs.push(err))
}
```
and if I happen to have extra errors because my file is wrong in more than one project context, then I see the concatted errors, even if they all happen to be for the same reason...

What scares me in saying this is that I think it would be a lot of work to go in this direction...
