### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/atom-typescript#913]
Hi, is this project dead? since @basarat left, no one seems to be answering the issues apart from the community. It would be such a shame if this would be true. VS Code has its nice perks, but misses a lot of potential from this plugin. Also, whole experience is just better in Atom. What is the status? Thanks in advance.

**Comment by basarat** [comment]
@tomitrescak is there a particular issue you are facing. I'm just not here day to day anymore but this is still the editor I am using (at least till [alm.tools](http://alm.tools/) can bootstrap itself) :rose: I'm just not adding/supporting features I don't have immediate need for :rose:

**Comment by tomitrescak** [comment]
Thanks for the fast reponse! Well, there are several issues, that are a bit painful.

1. Speed - having node_modules somewhere on the same level or above the tsconfig location kills the performance (about 10x slower)
2. Support for "project directory"

There are some other ones, but these are the most pending.
After ALM the Atom will be finished?

**Comment by basarat** [comment]
@tomitrescak valid concerns. Sorry I don't have an answer so leaving open for others :rose: 

> Speed - having node_modules somewhere on the same level or above the tsconfig location kills the performance

Long standing issue. I do hope you have `filesGlob` setup right : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#for-really-large-projects-atom-typescript-gets-slow (or put in `exclude`). 



> Support for "project directory

People started work on it https://github.com/TypeStrong/atom-typescript/pull/849 but indeed it seems abandoned. Because I don't use `systemjs` and use `commonjs` everywhere, I use relative file paths everywhere, so haven't had the time to look into it myself. 

> After ALM the Atom will be finished?

Probably not. Still a lot to do on ALM :). But if I feel that it *really is the best way* then maybe I won't pop in here much. I still like what we made here. We made it before VSCode was a thing to show that the TypeScript Language Service is truly awesome and VS was not giving you all the power. Now I am out to prove that its not just awesome, it can be the best way to uplift your aging JavaScript codebase :rose:

**Comment by tomitrescak** [comment]
I completely switched from JS to TS mostly because of the comfort and safety that was given to me with Atom + TS + this plugin. Working on prototype projects requires a lot of refactoring and that is just not doable with JS. VS code still has a long way to code before it reaches the comfort of this plugin. There are just outstanding issues that make it unusable. For example, constant false positives for errors, inability of compiling and emitting a single file, missing dedicated error pane ... and more.

Ha, and thanks for that FAQ page, I did not know I can use babel ... helps a lot for the use of Babel plugins! Awesome ;) :gift:

**Comment by laurelnaiad** [comment]
Re #849 what I was working on isn't abandoned. I use it. :) I simply have not had time to make it right or complete. But that code in #849 is far enough along that if I had any time to spend on atom-typescript, I'd be spending it thinking about the big picture question of tsconfig file interpretation generally.. issues that predate the `baseUrl` feature.

**Comment by basarat** [comment]
> For example, constant false positives for errors, inability of compiling and emitting a single file, missing dedicated error pane ... and more

My experience was similar. Hence I'm still working on that new thing. I feel that a *general purpose code editor with multi language support* cannot be the *best editor for TypeScript*. And the best editor for TypeScript might be too obtrusive for general purpose editing :rose:

**Comment by tomitrescak** [comment]
What scares me though is that you are using web editor for this. I use extensively AceEditor and CodeMirror but they are quite buggy after longer use. Atom had to bend it quite heavily for Electron to get the stable editing performance. Well, fingers crossed it will work out well! ;)

**Comment by basarat** [comment]
> Atom had to bend it quite heavily for Electron to get the stable editing performanc

Actually I have found the performance of CodeMirror (its used by chrome dev tools / Brackets / LightTable as well) to be most excellent. You can see it in action here https://www.youtube.com/watch?v=-oEa6UueHsk :rose: 

Multi monitor madness: 
![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/multiMonitor.gif)

**Comment by basarat** [comment]
A project of this magnitude does need constant love (especially as atom / typescript keep evolving). That love is somewhat lacking because: 

* VSCode TypeScript experience will continue to improve
* If I have to do something that truly compliments what Microsoft is already doing (:heart:) I have to do it as something super special that builds *around* TypeScript and not the other way around. 

Existing features are still supported. So in short the project is not dead. :rose:

**Comment by tomitrescak** [comment]
@basarat and I thank you for all the effort. It truly is a masterpiece plugin! Thanks for the feedback.

**Comment by ksachdeva** [comment]
@basarat I can tell you that every 3 weeks I give VS code a try and then come back to use atom and your extension. While it seems obvious to be concerned (or rather aware of) that VS Code will become good because of the backing it has, it is to be noted that lot of people will find atom and its extensions ecosystem (especially your wonderful typescript extension) useful and appropriate for their needs.

In simple words, it is not like that after VS code other editors (sublime, web storm etc) will stop supporting typescript.

In any case, many thanks for this wonderful work you have done on this extension.

**Comment by laurelnaiad** [comment]
There are a lot of us using atom-typescript. atom community is growing, typescript community is growing. I'm not worried about the future for atom-typescript. 

I just think there are some issues to address that nobody has yet stepped up to tackle. @basarat did a service by starting a conversation on the tsconfig situation in #910. 

In some important ways, atom-typescript remains ahead of other editors. I think to the extent we could come up with a good solution to tsconfig/file/project associations, it would really help the project to keep up.

**Comment by basarat** [comment]
Your concerns on the current state of available development tools for TypeScript has pushed me to wrap up the big issues I had with [alm.tools](http://alm.tools/) and start releasing it on NPM even in its current state for user review. It is now live :checkered_flag: ! https://www.npmjs.com/package/alm you can give it a go `npm install alm -g` 

Then `alm -o` in your project dir. It will start the web server and open the GUI in your default browser (will only work with chrome). 

----

@tomitrescak I feel that it already provides value and you might be pleasantly surprised. I did a lot of testing to make sure it behaves super smooth. A lot of the *modern IDE* features are there https://github.com/alm-tools/alm/blob/master/docs/features/README.md along with a few eccentric ones I wanted 🌹

This is just a *very* soft launch for initial feedback. So I still need to update the README / website to mention that its actually on NPM :+1: 

Please raise any issues here : https://github.com/alm-tools/alm/issues and if you like it [mention me](https://twitter.com/basarat) as that will keep my energy going :rose:
