### ISSUE TITLE
Feature: Function flow

### ISSUE THREAD

**Issue by danielbrodin** [TypeStrong/atom-typescript#941]
Hey,

First off, really like the package. Have just converted a medium sized project to use typescript and your package have really made the experience great and made me enjoy typescript.

Now to the feature. I think the dependency view is really nice and that got me thinking of a "similar"  feature. A function flow, where you pick a function and then get a flow of all functions it is calling. Then clicking on a function would take you to it. So it could pretty much look like the dependency view, but be built up of functions instead.

I hope it makes any sense :)

**Comment by basarat** [comment]
> A function flow, where you pick a function and then get a flow of all functions it is calling. Then clicking on a function would take you to it. So it could pretty much look like the dependency view, but be built up of functions instead

I definitely have plans for it in http://alm.tools/ I imagine a UI where one goes from (`function | class`) to another called `function | class` or another calling `function | class` :rose:

**Comment by jeffschwartz** [comment]
+
That would be a brilliant piece of kit if you ask me. It would definitely
assist refactoring as well as providing the ability to gleam insight into a
procedural flow. I'd volunteer myself to participate but I'm an Atom
virgin, so to speak :)

Sent from my iPad

On May 14, 2016, at 6:39 PM, Basarat Ali Syed <notifications@github.com>
wrote:

A function flow, where you pick a function and then get a flow of all
functions it is calling. Then clicking on a function would take you to it.
So it could pretty much look like the dependency view, but be built up of
functions instead

I definitely have plans for it in http://alm.tools/ I imagine a UI where
one goes from (function | class) to another called function | class or
another calling function | class [image: :rose:]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/TypeStrong/atom-typescript/issues/941#issuecomment-219255525>
