### ISSUE TITLE
Formatting eats text

### ISSUE THREAD

**Issue by kuon** [TypeStrong/atom-typescript#974]
The formatter often eats my text, like so:

``` js
      el.parentElement.insertBefore(wrapper, el)
```

after:

``` js
    .parentElement.insertBefore(wrapper, el)
```

it happens only if I have: `"formatOnSave": true` in my `tsconfig.json`.

**Comment by Clay-Ferguson** [comment]
This has to be a duplicate of 
https://github.com/TypeStrong/atom-typescript/issues/803

I had already made a guess that formatOnSave could be turned off to fix it, even before reading your note! So this gives the developers a lot to go on. 

I'm betting it's a concurrency bug. For now, the developers of this plugin need to completely disable formatOnSave because it VERY RELIABLY corrupts files in a very bad way. Randomly deletes a single characters from all over the file. This is litterally the worst kind of bug a text editor can have. Random single character corruptions that can easily go unnoticed and get checked into source control. If this is not their top priority, then it would be a HUGE mistake. They need to fix on this one ASAP, before it destroys the reputation of this plugin.

**Comment by Clay-Ferguson** [comment]
Note to develpers: When you remove the 'formatOnSave' please also change the CTRL+ALT+L to something else, because for Ubuntu users this cmd logs you out of Ubuntu completely. lol. Can't have my cake and format it too.

**Comment by kuon** [comment]
Yes, I think it's a concurrency bug too, the way the file is corrupted hint to this direction.

Of course, until it's fixed be sure to have `formatOnSave` to `false`.
